### ISSUE TITLE
why error?

### ISSUE THREAD

**Issue by Dragonfire75** [Iskallia/Vault-public#1102]
[19:50:20] [main/INFO]: ModLauncher running: args [--username, t....0, --version, t....5 1.16.5, --gameDir, ......., --assetsDir,....., --assetIndex, 1.16, --uuid, 2ef0131b-b375-11ea-8bba-b42e996a7d7a, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 900, --height, 500, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.39, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[19:50:20] [main/INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_351 by Oracle Corporation
[19:50:20] [main/INFO]: OptiFineTransformationService.onLoad
[19:50:20] [main/INFO]: OptiFine ZIP file: ......mods\OptiFine_1.16.5_HD_U_G8.jar
[19:50:20] [main/INFO]: Target.PRE_CLASS is available
[19:50:20] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[19:50:21] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:......./libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[19:50:21] [main/INFO]: OptiFineTransformationService.initialize
[19:50:24] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:0 token recognition error at: '`'
[19:50:24] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[19:50:24] [main/INFO]: OptiFineTransformationService.transformers
[19:50:24] [main/INFO]: Targets: 311
[19:50:26] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[19:50:26] [main/ERROR]: Mixin config boss_tools.mixin.json does not specify "minVersion" property
[19:50:26] [main/ERROR]: Mixin config notenoughcrashes.mixins.json does not specify "minVersion" property
[19:50:26] [main/ERROR]: Mixin config notenoughcrashes.forge.mixins.json does not specify "minVersion" property
[19:50:26] [main/ERROR]: Mixin config moreoverlays.mixin.json does not specify "minVersion" property
[19:50:26] [main/INFO]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
[19:50:26] [main/INFO]: Successfully loaded Mixin Connector [com.meteor.extrabotany.common.MixinConnector]
[19:50:26] [main/INFO]: Successfully loaded Mixin Connector [com.robertx22.age_of_exile.mmorpg.MixinConnector]
[19:50:26] [main/INFO]: Successfully loaded Mixin Connector [com.robertx22.library_of_exile.main.MixinConnector]
[19:50:26] [main/INFO]: Successfully loaded Mixin Connector [iskallia.vault.MixinConnector]
[19:50:26] [main/INFO]: Successfully loaded Mixin Connector [hellfirepvp.astralsorcery.MixinConnector]
[19:50:26] [main/INFO]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[19:50:26] [main/INFO]: Successfully loaded Mixin Connector [com.robertx22.world_of_exile.main.MixinConnector]
[19:50:26] [main/INFO]: Successfully loaded Mixin Connector [eutros.framedcompactdrawers.MixinConnector]
[19:50:26] [main/INFO]: Successfully loaded Mixin Connector [thelm.jaopca.mixins.JAOPCAMixinConnector]
[19:50:27] [main/INFO]: [com.robertx22.library_of_exile.main.MixinConnector:connect:10]: Connecting library_of_exile Mixins
[19:50:27] [main/INFO]: Launching target 'fmlclient' with arguments [--version,......., --gameDir, ......, --assetsDir, ...... --uuid, 2ef0131b-b375-11ea-8bba-b42e996a7d7a, --username, ....., --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 900, --height, 500]
[19:50:28] [main/WARN]: Reference map 'bloodsmeltery.refmap.json' for bloodsmeltery.mixin.json could not be read. If this is a development environment you can ignore this message
[19:50:29] [main/INFO]: Patching ModelBakery#<init>
[19:50:29] [main/INFO]: Patching CrossbowItem#onItemRightClick
[19:50:29] [main/INFO]: Patching CrossbowItem#fireProjectile
[19:50:30] [main/INFO]: Patching LivingEntity#attackEntityFrom
[19:50:30] [main/INFO]: Patching LivingEntity#blockUsingShield
[19:50:30] [main/INFO]: Patching LivingEntity#applyPotionDamageCalculations
[19:50:30] [main/ERROR]: Error occurred applying transform of coremod META-INF/asm/multipart.js function render
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(InsnList.java:343) ~[asm-tree-9.1.jar:9.1]
	at jdk.nashorn.internal.scripts.Script$Recompilation$109$5956A$\^eval\_.initializeCoreMod#transformer-3(<eval>:135) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117) ~[nashorn.jar:?]
	at net.minecraftforge.coremod.NashornFactory.lambda$getFunction$0(NashornFactory.java:18) ~[coremods-4.0.6.jar:4.0.6+14+master.c21a551]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:18) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:10) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) ~[coremods-4.0.6.jar:?]
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:111) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:142) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$null$8(LaunchPluginHandler.java:97) ~[modlauncher-8.1.3.jar:?]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.getClassNode(MixinLaunchPluginLegacy.java:222) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.getClassNode(MixinLaunchPluginLegacy.java:207) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:2005) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1017) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1007) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:895) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:867) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:779) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:539) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_351]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_351]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_351]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[19:50:31] [main/WARN]: Error loading class: shadows/fastbench/util/FastBenchUtil (java.lang.ClassNotFoundException: null)
[19:50:31] [main/WARN]: @Mixin target shadows.fastbench.util.FastBenchUtil was not found aoa3.mixins.json:common.function.FastBenchUtilMixin
[19:50:31] [main/INFO]: Adding 'reach_set_server_entity_interact' ASM patch...
[19:50:31] [main/INFO]: Added 'reach_set_server_entity_interact' ASM patch!
[19:50:31] [main/INFO]: Adding 'reach_set_server_entity_interact' ASM patch...
[19:50:31] [main/INFO]: Added 'reach_set_server_entity_interact' ASM patch!
[19:50:31] [main/INFO]: Adding 'reach_set_client_renderer' ASM patch...
[19:50:31] [main/INFO]: Added 'reach_set_client_renderer' ASM patch!
[19:50:32] [main/INFO]: Patching ItemStack#onItemUse
[19:50:33] [main/INFO]: Patching FishingBobberEntity#catchingFish
[19:50:33] [main/WARN]: Error loading class: net/minecraft/block/entity/LecternBlockEntity$1 (java.lang.ClassNotFoundException: null)
[19:50:33] [main/WARN]: @Mixin target net.minecraft.block.entity.LecternBlockEntity$1 was not found pehkui.mixins.json:reach.LecternBlockEntityMixin
[19:50:33] [main/INFO]: Adding 'on_block_change' ASM patch...
[19:50:33] [main/INFO]: Added 'on_block_change' ASM patch!
[19:50:33] [main/INFO]: Adding 'on_block_change' ASM patch...
[19:50:33] [main/INFO]: Added 'on_block_change' ASM patch!
[19:50:34] [main/INFO]: Patching DataPackRegistries#<init>
[19:50:35] [main/WARN]: Error loading class: net/minecraft/client/resources/language/ClientLanguage (java.lang.ClassNotFoundException: null)
[19:50:35] [main/WARN]: @Mixin target net.minecraft.client.resources.language.ClientLanguage was not found ellp.mixins-forge.json:MixinTranslationStorage
[19:50:35] [main/INFO]: Patching EnchantmentHelper#getEnchantmentModifierDamage
[19:50:35] [main/INFO]: Patching EnchantmentHelper#getModifierForCreature
[19:50:35] [main/INFO]: Patching EnchantmentHelper#applyThornEnchantments
[19:50:35] [main/INFO]: Patching EnchantmentHelper#applyArthropodEnchantments
[19:50:35] [main/INFO]: Patching buildEnchantmentList for the Enchantability affix.
[19:50:35] [main/INFO]: Patching EnchantmentHelper#getEnchantmentDatas
[19:50:35] [main/INFO]: Patching TemptGoal#isTempting
[19:50:36] [main/WARN]: Error loading class: tfar/dankstorage/item/DankItem (java.lang.ClassNotFoundException: null)
[19:50:36] [main/WARN]: @Mixin target tfar.dankstorage.item.DankItem was not found assets/the_vault/the_vault.mixins.json:MixinDankItem
[19:50:36] [main/INFO]: Patching RepairContainer#updateRepairOutput
[19:50:36] [main/INFO]: Successfully removed the anvil level cap.
[19:50:36] [main/INFO]: Patching RepairContainer#updateRepairOutput
[19:50:36] [main/INFO]: Successfully allowed nbt-unbreakable items in the anvil.
[19:50:36] [main/INFO]: Patching net/minecraft/inventory/container/RepairContainer
[19:50:36] [main/INFO]: Patching AnvilScreen#drawGuiContainerForegroundLayer
[19:50:36] [main/INFO]: Patching net/minecraft/item/EnchantedBookItem
[19:50:39] [main/INFO]: Adding 'on_block_change' ASM patch...
[19:50:39] [main/INFO]: Added 'on_block_change' ASM patch!
[19:50:39] [main/INFO]: Patching BlockModelShapes#getModelLocation
[19:50:40] [main/INFO]: Patching LivingEntity#attackEntityFrom
[19:50:40] [main/INFO]: Patching LivingEntity#blockUsingShield
[19:50:40] [main/INFO]: Patching LivingEntity#applyPotionDamageCalculations
[19:50:40] [main/ERROR]: Error occurred applying transform of coremod META-INF/asm/multipart.js function render
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(InsnList.java:343) ~[asm-tree-9.1.jar:9.1]
	at jdk.nashorn.internal.scripts.Script$Recompilation$109$5956A$\^eval\_.initializeCoreMod#transformer-3(<eval>:135) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117) ~[nashorn.jar:?]
	at net.minecraftforge.coremod.NashornFactory.lambda$getFunction$0(NashornFactory.java:18) ~[coremods-4.0.6.jar:4.0.6+14+master.c21a551]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:18) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:10) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) ~[coremods-4.0.6.jar:?]
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:111) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_351]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:307) ~[?:?]
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101) ~[?:?]
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54) ~[?:?]
	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:425) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:122) ~[......%201.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_351]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_351]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[19:50:40] [main/WARN]: @ModifyConstant conflict. Skipping assets/botania/botania.mixins.json:MixinWorldRenderer->@ModifyConstant::makeSunBigger(F)F with priority 1000, already redirected by mythicbotany.mixins.json:MixinWorldRenderer->@ModifyConstant::makeSunBigger(F)F with priority 1000
[19:50:40] [main/WARN]: @ModifyConstant conflict. Skipping assets/botania/botania.mixins.json:MixinWorldRenderer->@ModifyConstant::makeMoonBigger(F)F with priority 1000, already redirected by mythicbotany.mixins.json:MixinWorldRenderer->@ModifyConstant::makeMoonBigger(F)F with priority 1000
[19:50:40] [main/INFO]: Patching ItemStack#onItemUse
[19:50:41] [main/INFO]: Adding 'reach_set_client_renderer' ASM patch...
[19:50:41] [main/INFO]: Added 'reach_set_client_renderer' ASM patch!
[19:50:41] [main/WARN]: @ModifyConstant conflict. Skipping pehkui.mixins.json:reach.client.GameRendererMixin->@ModifyConstant::pehkui$updateTargetedEntity$squaredMaxDistance(DF)D with priority 990, already redirected by aoa3.mixins.json:client.patch.GameRendererMixin->@ModifyConstant::checkMaxRange(D)D with priority 1000
[19:50:43] [pool-3-thread-1/INFO]: Using Java 8 class definer
[19:50:43] [pool-3-thread-1/INFO]: Patching SharedMonsterAttributes#readAttributeModifier
[19:50:44] [pool-3-thread-1/WARN]: @Final field field_82223_h:[I in epicfight.mixins.json:MixinWitherBoss should be final
[19:50:44] [pool-3-thread-1/WARN]: @Final field field_82224_i:[I in epicfight.mixins.json:MixinWitherBoss should be final
[19:50:44] [pool-3-thread-1/INFO]: Patching RepairContainer#updateRepairOutput
[19:50:44] [pool-3-thread-1/INFO]: Successfully removed the anvil level cap.
[19:50:44] [pool-3-thread-1/INFO]: Patching RepairContainer#updateRepairOutput
[19:50:44] [pool-3-thread-1/INFO]: Successfully allowed nbt-unbreakable items in the anvil.
[19:50:44] [pool-3-thread-1/INFO]: Patching net/minecraft/inventory/container/RepairContainer
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.reflect.InvocationTargetException
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[19:50:44] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 4 more
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 10 more
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.block.Blocks.<clinit>(Blocks.java:394)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.LinkedHashMap.forEach(Unknown Source)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:50:44] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Thread.run(Unknown Source)
[19:50:44] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method overrideMaxRepairLevel(I)I in assets/the_vault/the_vault.mixins.json:MixinRepairContainer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap the_vault.refmap.json
[19:50:44] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[19:50:44] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[19:50:44] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[19:50:44] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[19:50:44] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[19:50:44] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[19:50:44] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[19:50:44] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[19:50:44] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	... 25 more

**Comment by Dragonfire75** [comment]
sorry mod OpenLoader
