### ISSUE TITLE
sorry error

### ISSUE THREAD

**Issue by Dragonfire75** [Iskallia/Vault-public#1104]
[00:03:34] [main/INFO]: ModLauncher running: args [--username, , --version, , --gameDir, , --assetsDir, , --assetIndex, 1.16, --uuid, 2ef0131b-b375-11ea-8bba-b42e996a7d7a, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 900, --height, 500, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.39, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[00:03:34] [main/INFO]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_351 by Oracle Corporation
[00:03:34] [main/INFO]: OptiFineTransformationService.onLoad
[00:03:34] [main/INFO]: OptiFine ZIP file: mods\OptiFine_1.16.5_HD_U_G8.jar
[00:03:34] [main/INFO]: Target.PRE_CLASS is available
[00:03:34] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[00:03:34] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[00:03:34] [main/INFO]: OptiFineTransformationService.initialize
[00:03:38] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:0 token recognition error at: '`'
[00:03:38] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[00:03:38] [main/INFO]: OptiFineTransformationService.transformers
[00:03:38] [main/INFO]: Targets: 311
[00:03:41] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[00:03:41] [main/ERROR]: Mixin config notenoughcrashes.mixins.json does not specify "minVersion" property
[00:03:41] [main/ERROR]: Mixin config notenoughcrashes.forge.mixins.json does not specify "minVersion" property
[00:03:41] [main/ERROR]: Mixin config moreoverlays.mixin.json does not specify "minVersion" property
[00:03:41] [main/INFO]: Successfully loaded Mixin Connector [shetiphian.core.mixins.MixinConnector]
[00:03:41] [main/INFO]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
[00:03:41] [main/INFO]: Successfully loaded Mixin Connector [com.meteor.extrabotany.common.MixinConnector]
[00:03:41] [main/INFO]: Successfully loaded Mixin Connector [com.robertx22.age_of_exile.mmorpg.MixinConnector]
[00:03:41] [main/INFO]: Successfully loaded Mixin Connector [com.robertx22.library_of_exile.main.MixinConnector]
[00:03:41] [main/INFO]: Successfully loaded Mixin Connector [iskallia.vault.MixinConnector]
[00:03:41] [main/INFO]: Successfully loaded Mixin Connector [hellfirepvp.astralsorcery.MixinConnector]
[00:03:41] [main/INFO]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[00:03:41] [main/INFO]: Successfully loaded Mixin Connector [de.maxhenkel.camera.MixinConnector]
[00:03:41] [main/INFO]: Successfully loaded Mixin Connector [com.robertx22.world_of_exile.main.MixinConnector]
[00:03:41] [main/INFO]: Successfully loaded Mixin Connector [eutros.framedcompactdrawers.MixinConnector]
[00:03:41] [main/INFO]: Successfully loaded Mixin Connector [thelm.jaopca.mixins.JAOPCAMixinConnector]
[00:03:41] [main/INFO]: [com.robertx22.library_of_exile.main.MixinConnector:connect:10]: Connecting library_of_exile Mixins
[00:03:41] [main/INFO]: Launching target 'fmlclient' with arguments [--version, , --gameDir, , --assetsDir, \assets, --uuid, 2ef0131b-b375-11ea-8bba-b42e996a7d7a, --username, , --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 900, --height, 500]
[00:03:43] [main/WARN]: Reference map 'bloodsmeltery.refmap.json' for bloodsmeltery.mixin.json could not be read. If this is a development environment you can ignore this message
[00:03:43] [main/INFO]: Patching ModelBakery#<init>
[00:03:44] [main/INFO]: Patching CrossbowItem#onItemRightClick
[00:03:44] [main/INFO]: Patching CrossbowItem#fireProjectile
[00:03:44] [main/INFO]: Patching LivingEntity#attackEntityFrom
[00:03:44] [main/INFO]: Patching LivingEntity#blockUsingShield
[00:03:44] [main/INFO]: Patching LivingEntity#applyPotionDamageCalculations
[00:03:44] [main/ERROR]: Error occurred applying transform of coremod META-INF/asm/multipart.js function render
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(InsnList.java:343) ~[asm-tree-9.1.jar:9.1]
	at jdk.nashorn.internal.scripts.Script$Recompilation$155$5956A$\^eval\_.initializeCoreMod#transformer-3(<eval>:135) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117) ~[nashorn.jar:?]
	at net.minecraftforge.coremod.NashornFactory.lambda$getFunction$0(NashornFactory.java:18) ~[coremods-4.0.6.jar:4.0.6+14+master.c21a551]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:18) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:10) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) ~[coremods-4.0.6.jar:?]
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:111) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:142) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$null$8(LaunchPluginHandler.java:97) ~[modlauncher-8.1.3.jar:?]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.getClassNode(MixinLaunchPluginLegacy.java:222) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.getClassNode(MixinLaunchPluginLegacy.java:207) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:2005) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1017) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1007) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:895) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:867) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:779) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:539) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.4.jar:0.8.4+Jenkins-b308.git-2accda5000f7602229606b39437565542cc6fba4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154) ~[modlauncher-8.1.3.jar:8.1.3+8.1.3+main-8.1.x.c94d18ec]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_351]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_351]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_351]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[00:03:45] [main/INFO]: Patching ItemStack#onItemUse
[00:03:46] [main/INFO]: Adding 'reach_set_server_entity_interact' ASM patch...
[00:03:46] [main/INFO]: Added 'reach_set_server_entity_interact' ASM patch!
[00:03:46] [main/INFO]: Adding 'reach_set_server_entity_interact' ASM patch...
[00:03:46] [main/INFO]: Added 'reach_set_server_entity_interact' ASM patch!
[00:03:46] [main/INFO]: Patching FishingBobberEntity#catchingFish
[00:03:46] [main/WARN]: Error loading class: net/minecraft/block/entity/LecternBlockEntity$1 (java.lang.ClassNotFoundException: null)
[00:03:46] [main/WARN]: @Mixin target net.minecraft.block.entity.LecternBlockEntity$1 was not found pehkui.mixins.json:reach.LecternBlockEntityMixin
[00:03:46] [main/INFO]: Adding 'on_block_change' ASM patch...
[00:03:46] [main/INFO]: Added 'on_block_change' ASM patch!
[00:03:46] [main/INFO]: Adding 'reach_set_client_renderer' ASM patch...
[00:03:46] [main/INFO]: Added 'reach_set_client_renderer' ASM patch!
[00:03:47] [main/INFO]: Adding 'on_block_change' ASM patch...
[00:03:47] [main/INFO]: Added 'on_block_change' ASM patch!
[00:03:47] [main/INFO]: Patching DataPackRegistries#<init>
[00:03:49] [main/WARN]: Error loading class: net/minecraft/client/resources/language/ClientLanguage (java.lang.ClassNotFoundException: null)
[00:03:49] [main/WARN]: @Mixin target net.minecraft.client.resources.language.ClientLanguage was not found ellp.mixins-forge.json:MixinTranslationStorage
[00:03:49] [main/INFO]: Patching EnchantmentHelper#getEnchantmentModifierDamage
[00:03:49] [main/INFO]: Patching EnchantmentHelper#getModifierForCreature
[00:03:49] [main/INFO]: Patching EnchantmentHelper#applyThornEnchantments
[00:03:49] [main/INFO]: Patching EnchantmentHelper#applyArthropodEnchantments
[00:03:49] [main/INFO]: Patching buildEnchantmentList for the Enchantability affix.
[00:03:49] [main/INFO]: Patching EnchantmentHelper#getEnchantmentDatas
[00:03:49] [main/INFO]: Patching TemptGoal#isTempting
[00:03:50] [main/WARN]: Error loading class: tfar/dankstorage/item/DankItem (java.lang.ClassNotFoundException: null)
[00:03:50] [main/WARN]: @Mixin target tfar.dankstorage.item.DankItem was not found assets/the_vault/the_vault.mixins.json:MixinDankItem
[00:03:50] [main/INFO]: Patching RepairContainer#updateRepairOutput
[00:03:50] [main/INFO]: Successfully removed the anvil level cap.
[00:03:50] [main/INFO]: Patching RepairContainer#updateRepairOutput
[00:03:50] [main/INFO]: Successfully allowed nbt-unbreakable items in the anvil.
[00:03:50] [main/INFO]: Patching net/minecraft/inventory/container/RepairContainer
[00:03:50] [main/INFO]: Patching AnvilScreen#drawGuiContainerForegroundLayer
[00:03:50] [main/INFO]: Patching net/minecraft/item/EnchantedBookItem
[00:03:52] [main/INFO]: Adding 'on_block_change' ASM patch...
[00:03:52] [main/INFO]: Added 'on_block_change' ASM patch!
[00:03:52] [main/INFO]: Patching BlockModelShapes#getModelLocation
[00:03:53] [main/INFO]: Patching LivingEntity#attackEntityFrom
[00:03:53] [main/INFO]: Patching LivingEntity#blockUsingShield
[00:03:53] [main/INFO]: Patching LivingEntity#applyPotionDamageCalculations
[00:03:53] [main/ERROR]: Error occurred applying transform of coremod META-INF/asm/multipart.js function render
java.lang.NullPointerException: null
	at org.objectweb.asm.tree.InsnList.insert(InsnList.java:343) ~[asm-tree-9.1.jar:9.1]
	at jdk.nashorn.internal.scripts.Script$Recompilation$155$5956A$\^eval\_.initializeCoreMod#transformer-3(<eval>:135) ~[?:?]
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:639) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494) ~[nashorn.jar:?]
	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393) ~[nashorn.jar:?]
	at jdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:117) ~[nashorn.jar:?]
	at net.minecraftforge.coremod.NashornFactory.lambda$getFunction$0(NashornFactory.java:18) ~[coremods-4.0.6.jar:4.0.6+14+master.c21a551]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:18) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModMethodTransformer.runCoremod(CoreModMethodTransformer.java:10) ~[coremods-4.0.6.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) ~[coremods-4.0.6.jar:?]
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:111) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136) ~[modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_351]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:307) ~[?:?]
	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101) ~[?:?]
	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54) ~[?:?]
	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:425) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:122) ~[%201.16.5.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_351]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_351]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_351]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37) ~[forge-1.16.5-36.2.39.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
[00:03:53] [main/WARN]: @ModifyConstant conflict. Skipping assets/botania/botania.mixins.json:MixinWorldRenderer->@ModifyConstant::makeSunBigger(F)F with priority 1000, already redirected by mythicbotany.mixins.json:MixinWorldRenderer->@ModifyConstant::makeSunBigger(F)F with priority 1000
[00:03:53] [main/WARN]: @ModifyConstant conflict. Skipping assets/botania/botania.mixins.json:MixinWorldRenderer->@ModifyConstant::makeMoonBigger(F)F with priority 1000, already redirected by mythicbotany.mixins.json:MixinWorldRenderer->@ModifyConstant::makeMoonBigger(F)F with priority 1000
[00:03:53] [main/INFO]: Patching ItemStack#onItemUse
[00:03:54] [main/INFO]: Adding 'reach_set_client_renderer' ASM patch...
[00:03:54] [main/INFO]: Added 'reach_set_client_renderer' ASM patch!
[00:03:57] [pool-3-thread-1/INFO]: Using Java 8 class definer
[00:03:57] [pool-3-thread-1/INFO]: Patching SharedMonsterAttributes#readAttributeModifier
[00:03:58] [pool-3-thread-1/WARN]: @Final field field_82223_h:[I in epicfight.mixins.json:MixinWitherBoss should be final
[00:03:58] [pool-3-thread-1/WARN]: @Final field field_82224_i:[I in epicfight.mixins.json:MixinWitherBoss should be final
[00:03:58] [pool-3-thread-1/INFO]: Patching RepairContainer#updateRepairOutput
[00:03:58] [pool-3-thread-1/INFO]: Successfully removed the anvil level cap.
[00:03:58] [pool-3-thread-1/INFO]: Patching RepairContainer#updateRepairOutput
[00:03:58] [pool-3-thread-1/INFO]: Successfully allowed nbt-unbreakable items in the anvil.
[00:03:58] [pool-3-thread-1/INFO]: Patching net/minecraft/inventory/container/RepairContainer
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.reflect.InvocationTargetException
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:37)
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[00:03:58] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 4 more
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 10 more
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.block.Blocks.<clinit>(Blocks.java:394)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.LinkedHashMap.forEach(Unknown Source)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[00:03:58] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Thread.run(Unknown Source)
[00:03:58] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method overrideMaxRepairLevel(I)I in assets/the_vault/the_vault.mixins.json:MixinRepairContainer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap the_vault.refmap.json
[00:03:58] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
[00:03:58] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
[00:03:58] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
[00:03:58] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
[00:03:58] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
[00:03:58] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
[00:03:58] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
[00:03:58] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[00:03:58] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:-1]: 	... 25 more

**Comment by Dragonfire75** [comment]
Sorry
