### ISSUE TITLE
VH crashes when loading a server

### ISSUE THREAD

**Issue by bennyther** [Iskallia/Vault-public#1136]
I'm creating a vault hunters server, and when I try to load it, it does not work because of something in the vault mod. I had to change some things about other mods to get them to load. In torohealth I change the side from "CLIENT" to "SERVER". In the legendary tooltips mod I changed the version from "40.1," to "40.1.61" to work with the forge version, and now they work. Idk what the issue is but the Exception message is "java.lang.NullPointerException: Cannot invoke "iskallia.vault.core.world.processor.Palette.getTileProcessors()" because "palette" is null". I am running vault hunters 3rd edition and have java 17 installed.
Here's the full crash report:

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/29/22, 6:15 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.18.2-40.1.61-universal.jar%23173!/:?] {re:classloading}
	at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:39) ~[forge-1.18.2-40.1.61-universal.jar%23173!/:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23168!/:?] {re:classloading,re:mixin,pl:mixin:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.1.61.jar%2317!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at iskallia.vault.init.ModConfigs.registerGen(ModConfigs.java:280) ~[the_vault-1.18.2-2.0.8.763.jar%23153!/:1.18.2-2.0.8.763] {re:mixin,re:classloading}
-- MOD the_vault --
Details:
	Mod File: the_vault-1.18.2-2.0.8.763.jar
	Failure message: The Vault (the_vault) encountered an error during the common_setup event phase
		java.lang.NullPointerException: Cannot invoke "iskallia.vault.core.world.processor.Palette.getTileProcessors()" because "palette" is null
	Mod Version: 1.18.2-2.0.8.763
	Mod Issue URL: https://github.com/Iskallia/Vault/issues
	Exception message: java.lang.NullPointerException: Cannot invoke "iskallia.vault.core.world.processor.Palette.getTileProcessors()" because "palette" is null
Stacktrace:
	at iskallia.vault.init.ModConfigs.registerGen(ModConfigs.java:280) ~[the_vault-1.18.2-2.0.8.763.jar%23153!/:1.18.2-2.0.8.763] {re:mixin,re:classloading}
	at iskallia.vault.event.SetupEvents.setupCommon(SetupEvents.java:17) ~[the_vault-1.18.2-2.0.8.763.jar%23153!/:1.18.2-2.0.8.763] {re:classloading,pl:eventbus:A}
	at net.minecraftforge.eventbus.ASMEventHandler_495_SetupEvents_setupCommon_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.61.jar%23170!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.61.jar%23169!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.5, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 2100453888 bytes (2003 MiB) / 2711617536 bytes (2586 MiB) up to 4276092928 bytes (4078 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3400G with Radeon Vega Graphics    
	Identifier: AuthenticAMD Family 23 Model 24 Stepping 1
	Microarchitecture: Zen / Zen+
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1650
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f82
	Graphics card #0 versionInfo: DriverVersion=30.0.14.9649
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 31159.42
	Virtual memory used (MB): 12036.18
	Swap memory total (MB): 14848.00
	Swap memory used (MB): 236.01
	JVM Flags: 0 total; 
	ModLauncher: 9.1.3+9.1.3+main.9b69c82a
	ModLauncher launch target: forgeserver
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 slf4jfixer PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		kotori_scala@2.13.8-build-4
		javafml@null
	Mod List: 
		rsrequestify-2.2.0.jar                            |RSRequestify                  |rsrequestify                  |2.2.0               |SIDED_SETU|Manifest: NOSIGNATURE
		CyclopsCore-1.18.2-1.15.1.jar                     |Cyclops Core                  |cyclopscore                   |1.15.1              |SIDED_SETU|Manifest: NOSIGNATURE
		auudio_forge_1.0.3_MC_1.18-1.18.2.jar             |Auudio                        |auudio                        |1.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		supermartijn642configlib-1.1.6-forge-mc1.18.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6               |SIDED_SETU|Manifest: NOSIGNATURE
		Architects-Palette-1.18.2-1.2.0.jar               |Architect's Palette           |architects_palette            |1.1.2               |SIDED_SETU|Manifest: NOSIGNATURE
		cagerium-1.18.2-1.0.8.jar                         |cagerium                      |cagerium                      |1.18.2-1.0.8        |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-windows-2.0.3-mc1.18.2.jar                    |Macaw's Windows               |mcwwindows                    |2.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		sophisticatedcore-1.18.2-0.5.15.141.jar           |Sophisticated Core            |sophisticatedcore             |1.18.2-0.5.15.141   |SIDED_SETU|Manifest: NOSIGNATURE
		InitialInventory-forge-1.18.2-6.0.8.jar           |Initial Inventory             |initialinventory              |6.0.8               |SIDED_SETU|Manifest: NOSIGNATURE
		IronGenerators-2.0.2-1.18.2.jar                   |Iron Generators               |irongenerators                |2.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		XaerosWorldMap_1.25.1_Forge_1.18.2.jar            |Xaero's World Map             |xaeroworldmap                 |1.25.1              |SIDED_SETU|Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.18.2-12.0.2.jar      |CookingForBlockheads          |cookingforblockheads          |12.0.2              |SIDED_SETU|Manifest: NOSIGNATURE
		Controlling-forge-1.18.2-9.0+21.jar               |Controlling                   |controlling                   |9.0+21              |SIDED_SETU|Manifest: NOSIGNATURE
		Placebo-1.18.2-6.4.1.jar                          |Placebo                       |placebo                       |6.4.1               |SIDED_SETU|Manifest: NOSIGNATURE
		citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |SIDED_SETU|Manifest: NOSIGNATURE
		alexsmobs-1.18.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.6              |SIDED_SETU|Manifest: NOSIGNATURE
		Powah-3.0.1-beta.jar                              |Powah                         |powah                         |3.0.1-beta          |SIDED_SETU|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.18.2-13.2.50.jar                |Bookshelf                     |bookshelf                     |13.2.50             |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		lootbeams-1.18.1-release-july1722.jar             |LootBeams                     |lootbeams                     |1.18.1              |SIDED_SETU|Manifest: NOSIGNATURE
		twigs-forge-1.1.4-patch3+1.18.2.jar               |Twigs                         |twigs                         |1.1.4-patch1+1.18.2 |SIDED_SETU|Manifest: NOSIGNATURE
		buildinggadgets-3.13.0-build.5+mc1.18.2.jar       |Building Gadgets              |buildinggadgets               |3.13.0-build.5+mc1.1|SIDED_SETU|Manifest: NOSIGNATURE
		DarkUtilities-Forge-1.18.2-10.0.5.jar             |DarkUtilities                 |darkutils                     |10.0.5              |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-doors-1.0.6-mc1.18.2.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.6               |SIDED_SETU|Manifest: NOSIGNATURE
		MekanismGenerators-1.18.2-10.2.5.465.jar          |Mekanism: Generators          |mekanismgenerators            |10.2.5              |SIDED_SETU|Manifest: NOSIGNATURE
		balm-3.2.0+0.jar                                  |Balm                          |balm                          |3.2.0+0             |SIDED_SETU|Manifest: NOSIGNATURE
		JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |SIDED_SETU|Manifest: NOSIGNATURE
		cloth-config-7.0.72-forge.jar                     |Cloth Config v4 API           |cloth_config                  |7.0.72              |SIDED_SETU|Manifest: NOSIGNATURE
		shetiphiancore-1.18-3.10.10.jar                   |ShetiPhian-Core               |shetiphiancore                |3.10.10             |SIDED_SETU|Manifest: NOSIGNATURE
		MmmMmmMmmMmm-1.18.2-1.5.2.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.18-1.5.2          |SIDED_SETU|Manifest: NOSIGNATURE
		refinedstorage-1.10.2.jar                         |Refined Storage               |refinedstorage                |1.10.2              |SIDED_SETU|Manifest: NOSIGNATURE
		konkrete_forge_1.3.3_MC_1.18-1.18.1.jar           |Konkrete                      |konkrete                      |1.3.3               |SIDED_SETU|Manifest: NOSIGNATURE
		easy_piglins-1.18.2-1.0.0.jar                     |Easy Piglins                  |easy_piglins                  |1.18.2-1.0.0        |SIDED_SETU|Manifest: NOSIGNATURE
		corpse-1.18.2-1.0.2.jar                           |Corpse                        |corpse                        |1.18.2-1.0.2        |SIDED_SETU|Manifest: NOSIGNATURE
		PackMenu-1.18.2-4.1.3.jar                         |PackMenu                      |packmenu                      |4.1.3               |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-bridges-2.0.3-mc1.18.2.jar                    |Macaw's Bridges               |mcwbridges                    |2.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		torchmaster-18.1.0.jar                            |Torchmaster                   |torchmaster                   |18.1.0              |SIDED_SETU|Manifest: NOSIGNATURE
		Compressium-1.4.1-build.6+mc1.18.2.jar            |Compressium                   |compressium                   |1.4.1-build.6+mc1.18|SIDED_SETU|Manifest: NOSIGNATURE
		Ping-1.18-1.8.0.jar                               |Ping                          |ping                          |1.18-1.8.0          |SIDED_SETU|Manifest: NOSIGNATURE
		ironfurnaces-1.18.2-3.3.1.jar                     |Iron Furnaces                 |ironfurnaces                  |3.3.1               |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-trapdoors-1.0.6-mc1.18.2.jar                  |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.6               |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-fences-1.0.5-mc1.18.2.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.5               |SIDED_SETU|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.19-forge-mc1.18.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |SIDED_SETU|Manifest: NOSIGNATURE
		simplylight-1.18.2-1.4.2-build.31.jar             |Simply Light                  |simplylight                   |1.18.2-1.4.2-build.3|SIDED_SETU|Manifest: NOSIGNATURE
		Botania-1.18.2-434.jar                            |Botania                       |botania                       |1.18.2-434          |SIDED_SETU|Manifest: NOSIGNATURE
		Highlighter-1.18.1-1.1.2.jar                      |Highlighter                   |highlighter                   |1.1.2               |SIDED_SETU|Manifest: NOSIGNATURE
		spark-1.9.11-forge.jar                            |spark                         |spark                         |1.9.11              |SIDED_SETU|Manifest: NOSIGNATURE
		curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |SIDED_SETU|Manifest: NOSIGNATURE
		Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |SIDED_SETU|Manifest: NOSIGNATURE
		camera-1.18.2-1.0.4.jar                           |Camera Mod                    |camera                        |1.18.2-1.0.4        |SIDED_SETU|Manifest: NOSIGNATURE
		blockcarpentry-1.18-0.3.0.jar                     |BlockCarpentry                |blockcarpentry                |1.18-0.3.0          |SIDED_SETU|Manifest: NOSIGNATURE
		libnonymous-2.1.0.jar                             |libnonymous                   |libnonymous                   |2.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		elevatorid-1.18.2-1.8.4.jar                       |Elevator Mod                  |elevatorid                    |1.18.2-1.8.4        |SIDED_SETU|Manifest: NOSIGNATURE
		Runelic-Forge-1.18.2-11.0.1.jar                   |Runelic                       |runelic                       |11.0.1              |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		cfm-7.0.0-pre29-1.18.2.jar                        |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre29         |SIDED_SETU|Manifest: NOSIGNATURE
		architectury-4.9.84-forge.jar                     |Architectury                  |architectury                  |4.9.84              |SIDED_SETU|Manifest: NOSIGNATURE
		AuxiliaryBlocks-1.18.2-0.0.14.jar                 |Auxiliary Blocks              |auxiliaryblocks               |1.18.2-0.0.14       |SIDED_SETU|Manifest: NOSIGNATURE
		weirdinggadget-1.18.1-2.2.11.jar                  |The Weirding Gadget           |weirdinggadget                |2.2.11              |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-furniture-3.0.0-mc1.18.2.jar                  |Macaw's Furniture             |mcwfurnitures                 |3.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
		trashcans-1.0.15-forge-mc1.18.jar                 |Trash Cans                    |trashcans                     |1.0.15              |SIDED_SETU|Manifest: NOSIGNATURE
		mcw-lights-1.0.3-mc1.18.2.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
		Cucumber-1.18.2-5.1.2.jar                         |Cucumber Library              |cucumber                      |5.1.2               |SIDED_SETU|Manifest: NOSIGNATURE
		Snad-1.18.2-1.22.04.15a.jar                       |Snad                          |snad                          |1.18.2-1.22.04.15a  |SIDED_SETU|Manifest: NOSIGNATURE
		jei-1.18.2-9.7.0.209.jar                          |Just Enough Items             |jei                           |9.7.0.209           |SIDED_SETU|Manifest: NOSIGNATURE
		bdlib-1.19.3.7-mc1.18.2.jar                       |BdLib                         |bdlib                         |1.19.3.7            |SIDED_SETU|Manifest: NOSIGNATURE
		waystones-forge-1.18.2-10.1.0.jar                 |Waystones                     |waystones                     |10.1.0              |SIDED_SETU|Manifest: NOSIGNATURE
		Clumps-forge-1.18.2-8.0.0+10.jar                  |Clumps                        |clumps                        |8.0.0+10            |SIDED_SETU|Manifest: NOSIGNATURE
		shutupexperimentalsettings-1.0.5.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.5               |SIDED_SETU|Manifest: NOSIGNATURE
		comforts-forge-1.18.2-5.0.0.4.jar                 |Comforts                      |comforts                      |1.18.2-5.0.0.4      |SIDED_SETU|Manifest: NOSIGNATURE
		NaturesCompass-1.18.2-1.9.7-forge.jar             |Nature's Compass              |naturescompass                |1.18.2-1.9.7-forge  |SIDED_SETU|Manifest: NOSIGNATURE
		SimpleStorageNetwork-1.18.2-1.6.1.jar             |Simple Storage Network        |storagenetwork                |1.18.2-1.6.1        |SIDED_SETU|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		framedcompactdrawers-1.18-4.1.0.jar               |Framed Compacting Drawers     |framedcompactdrawers          |1.18-4.1.0          |SIDED_SETU|Manifest: NOSIGNATURE
		Decorative Blocks-forge-1.18.2-2.1.0.jar          |Decorative Blocks             |decorative_blocks             |2.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
		BotanyPots-Forge-1.18.2-8.0.12.jar                |BotanyPots                    |botanypots                    |8.0.12              |SIDED_SETU|Manifest: NOSIGNATURE
		ftbbackups2-forge-1.18.2-1.0.13.jar               |FTB Backups 2                 |ftbbackups2                   |1.0.13              |SIDED_SETU|Manifest: 59:0f:44:4b:f7:95:28:28:25:5b:fd:c0:c9:48:6c:4a:e5:6e:6d:7b:63:ab:f4:90:55:1f:cf:4b:e9:51:91:ed
		mcjtylib-1.18-6.0.15.jar                          |McJtyLib                      |mcjtylib                      |1.18-6.0.15         |SIDED_SETU|Manifest: NOSIGNATURE
		rftoolsbase-1.18-3.0.9.jar                        |RFToolsBase                   |rftoolsbase                   |1.18-3.0.9          |SIDED_SETU|Manifest: NOSIGNATURE
		xnet-1.18-4.0.5.jar                               |XNet                          |xnet                          |1.18-4.0.5          |SIDED_SETU|Manifest: NOSIGNATURE
		ispawner-1.0.3-forge.jar                          |iSpawner                      |ispawner                      |1.0                 |SIDED_SETU|Manifest: NOSIGNATURE
		everycomp-1.18.2-1.5.7.jar                        |Every Compat                  |everycomp                     |1.18.2-1.5.7        |SIDED_SETU|Manifest: NOSIGNATURE
		JEITweaker-1.18.2-3.0.0.8.jar                     |JEI Tweaker                   |jeitweaker                    |3.0.0.8             |SIDED_SETU|Manifest: NOSIGNATURE
		Terralith_v2.2.3.jar                              |Terralith                     |terralith                     |0.0NONE             |SIDED_SETU|Manifest: NOSIGNATURE
		mininggadgets-1.11.0.jar                          |Mining Gadgets                |mininggadgets                 |1.11.0              |SIDED_SETU|Manifest: NOSIGNATURE
		CraftTweaker-forge-1.18.2-9.1.197.jar             |CraftTweaker                  |crafttweaker                  |9.1.197             |SIDED_SETU|Manifest: NOSIGNATURE
		Mekanism-1.18.2-10.2.5.465.jar                    |Mekanism                      |mekanism                      |10.2.5              |SIDED_SETU|Manifest: NOSIGNATURE
		forge-1.18.2-40.1.61-universal.jar                |Forge                         |forge                         |40.1.61             |SIDED_SETU|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		Waddles-1.18.2-0.8.19.jar                         |Waddles                       |waddles                       |1.18.2-0.8.19       |SIDED_SETU|Manifest: NOSIGNATURE
		ColossalChests-1.18.2-1.8.3.jar                   |ColossalChests                |colossalchests                |1.8.3               |SIDED_SETU|Manifest: NOSIGNATURE
		selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |SIDED_SETU|Manifest: NOSIGNATURE
		supplementaries-1.18.2-1.5.13.jar                 |Supplementaries               |supplementaries               |1.18.2-1.5.13       |SIDED_SETU|Manifest: NOSIGNATURE
		drippyloadingscreen_forge_1.6.4_MC_1.18-1.18.2.jar|Drippy Loading Screen         |drippyloadingscreen           |1.6.4               |SIDED_SETU|Manifest: NOSIGNATURE
		craftingtweaks-forge-1.18.2-14.0.3.jar            |CraftingTweaks                |craftingtweaks                |14.0.3              |SIDED_SETU|Manifest: NOSIGNATURE
		server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |SIDED_SETU|Manifest: NOSIGNATURE
		cofh_core-1.18.2-1.6.4.21.jar                     |CoFH Core                     |cofh_core                     |1.6.4.21            |SIDED_SETU|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_foundation-1.18.2-1.6.3.28.jar            |Thermal Series                |thermal                       |1.6.3.28            |SIDED_SETU|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_expansion-1.18.2-1.6.3.13.jar             |Thermal Expansion             |thermal_expansion             |1.6.3.13            |SIDED_SETU|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		TerraBlender-forge-1.18.2-1.1.0.102.jar           |TerraBlender                  |terrablender                  |1.18.2-1.1.0.102    |SIDED_SETU|Manifest: NOSIGNATURE
		sophisticatedbackpacksvh-1.18.2-1.0.4.12.jar      |Sophisticated Backpacks Vault |sophisticatedbackpacksvh      |1.18.2-1.0.4.12     |SIDED_SETU|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.2-3.18.29.718.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.18.29.718  |SIDED_SETU|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |SIDED_SETU|Manifest: NOSIGNATURE
		titanium-1.18.2-3.5.6-38.jar                      |Titanium                      |titanium                      |3.5.6               |SIDED_SETU|Manifest: NOSIGNATURE
		Jade-1.18.2-forge-5.2.3.jar                       |Jade                          |jade                          |5.2.3               |SIDED_SETU|Manifest: NOSIGNATURE
		appliedenergistics2-11.1.4.jar                    |Applied Energistics 2         |ae2                           |11.1.4              |SIDED_SETU|Manifest: NOSIGNATURE
		CreateTweaker-1.18.2-2.0.0.17.jar                 |CreateTweaker                 |createtweaker                 |2.0.0.17            |SIDED_SETU|Manifest: NOSIGNATURE
		easy_villagers-1.18.2-1.0.10.jar                  |Easy Villagers                |easy_villagers                |1.18.2-1.0.10       |SIDED_SETU|Manifest: NOSIGNATURE
		pipez-1.18.2-1.1.5.jar                            |Pipez                         |pipez                         |1.18.2-1.1.5        |SIDED_SETU|Manifest: NOSIGNATURE
		Iceberg-1.18.2-1.0.44.jar                         |Iceberg                       |iceberg                       |1.0.44              |SIDED_SETU|Manifest: NOSIGNATURE
		flywheel-forge-1.18.2-0.6.5.jar                   |Flywheel                      |flywheel                      |0.6.5               |SIDED_SETU|Manifest: NOSIGNATURE
		create-1.18.2-0.5.0.d.jar                         |Create                        |create                        |0.5.0.d             |SIDED_SETU|Manifest: NOSIGNATURE
		Mantle-1.18.2-1.9.27.jar                          |Mantle                        |mantle                        |1.9.27              |SIDED_SETU|Manifest: NOSIGNATURE
		ecologics-forge-1.18.2-1.7.3.jar                  |Ecologics                     |ecologics                     |1.7.3               |SIDED_SETU|Manifest: NOSIGNATURE
		Xaeros_Minimap_22.11.1_Forge_1.18.2.jar           |Xaero's Minimap               |xaerominimap                  |22.11.1             |SIDED_SETU|Manifest: NOSIGNATURE
		PigPen-Forge-1.18.2-8.0.1.jar                     |PigPen                        |pigpen                        |8.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
		FastWorkbench-1.18.2-6.0.2.jar                    |Fast Workbench                |fastbench                     |6.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
		polymorph-forge-1.18.2-0.44.jar                   |Polymorph                     |polymorph                     |1.18.2-0.44         |SIDED_SETU|Manifest: NOSIGNATURE
		AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |SIDED_SETU|Manifest: NOSIGNATURE
		AkashicTome-1.5-20.jar                            |Akashic Tome                  |akashictome                   |1.5-20              |SIDED_SETU|Manifest: NOSIGNATURE
		Quark-3.2-358.jar                                 |Quark                         |quark                         |3.2-358             |SIDED_SETU|Manifest: NOSIGNATURE
		StorageDrawers-1.18.2-10.2.1.jar                  |Storage Drawers               |storagedrawers                |10.2.1              |SIDED_SETU|Manifest: NOSIGNATURE
		FluxNetworks-1.18.2-7.0.7.8.jar                   |Flux Networks                 |fluxnetworks                  |7.0.7.8             |SIDED_SETU|Manifest: NOSIGNATURE
		neoncraft2-2.2.jar                                |Neon Craft 2                  |neoncraft2                    |2.2                 |SIDED_SETU|Manifest: NOSIGNATURE
		enercell-1.18.2-1.0.2.jar                         |Enercell                      |enercell                      |0.0NONE             |SIDED_SETU|Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.4.0.jar                  |AppleSkin                     |appleskin                     |2.4.0+mc1.18        |SIDED_SETU|Manifest: NOSIGNATURE
		ferritecore-4.2.1-forge.jar                       |Ferrite Core                  |ferritecore                   |0.0NONE             |SIDED_SETU|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		modular-routers-1.18.2-9.1.1-93.jar               |Modular Routers               |modularrouters                |9.1.1-93            |SIDED_SETU|Manifest: NOSIGNATURE
		refinedstorageaddons-0.8.2.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.8.2               |SIDED_SETU|Manifest: NOSIGNATURE
		OpenLoader-Forge-1.18.2-12.0.1.jar                |OpenLoader                    |openloader                    |12.0.1              |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		the_vault-1.18.2-2.0.8.763.jar                    |The Vault                     |the_vault                     |1.18.2-2.0.8.763    |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 1c4dbd00-299f-4c6a-a959-40c0dd721262
	FML: 40.1
	Forge: net.minecraftforge:40.1.61

**Comment by jmilthedude** [comment]
Firstly, did you download the server pack? Those mods you mention shouldn’t be on the server. Secondly, you are missing config files if you get that error.

**Comment by bennyther** [comment]
okay I just checked I didn't download the server pack, thanks for helping
