### ISSUE TITLE
Mod Lod Failure on New Server "pool" is null

### ISSUE THREAD

**Issue by Blaksey** [Iskallia/Vault-public#1208]
**Describe the bug**
I just setup a new Ubuntu 22.04 server and installed openjdk 17.0.5 and tried to setup VaultHunters 6H.

Full error at the bottom

**To Reproduce**
1. Install fresh forge server via `forge-1.18.2-40.2.0-installer.jar --installServer`
2. Start server via run.sh, modify the eula 
3. Copy mods from local CurseForge VaultHunters Update-6H mods directory to the server mods directory
4. Start server via run.sh, wait until it crashes during start-up

**Expected behavior**
Normal server start-up

**Screenshots or Crash Report**
If applicable, add screenshots or crash reports to help explain your problem.

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version 1.18.2-2.0.14.1200

**Additional context**

```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
        at iskallia.vault.init.ModConfigs.registerGen(ModConfigs.java:311) ~[the_vault-1.18.2-2.0.14.1200.jar%23155!/:1.18.2-2.0.14.1200] {re:mixin,re:classloading}
-- MOD the_vault --
Details:
        Mod File: /home/ubuntu/mcserver/mods/the_vault-1.18.2-2.0.14.1200.jar
        Failure message: The Vault (the_vault) encountered an error during the common_setup event phase
                java.lang.NullPointerException: Cannot invoke "iskallia.vault.core.world.template.data.TemplatePool.iterate(java.util.function.Predicate)" because "pool" is null
        Mod Version: 1.18.2-2.0.14.1200
        Mod Issue URL: https://github.com/Iskallia/Vault/issues
        Exception message: java.lang.NullPointerException: Cannot invoke "iskallia.vault.core.world.template.data.TemplatePool.iterate(java.util.function.Predicate)" because "pool" is null
Stacktrace:
        at iskallia.vault.init.ModConfigs.registerGen(ModConfigs.java:311) ~[the_vault-1.18.2-2.0.14.1200.jar%23155!/:1.18.2-2.0.14.1200] {re:mixin,re:classloading}
        at iskallia.vault.event.SetupEvents.setupCommon(SetupEvents.java:17) ~[the_vault-1.18.2-2.0.14.1200.jar%23155!/:1.18.2-2.0.14.1200] {re:classloading,pl:eventbus:A}
        at net.minecraftforge.eventbus.ASMEventHandler_519_SetupEvents_setupCommon_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?] {}
        at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?] {}
        at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.2.0.jar%23171!/:?] {}
        at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.2.0.jar%23170!/:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
        Minecraft Version: 1.18.2
        Minecraft Version ID: 1.18.2
        Operating System: Linux (aarch64) version 5.15.0-1021-oracle
        Java Version: 17.0.5, Private Build
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Private Build
        Memory: 1120952320 bytes (1069 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
        CPUs: 4
        Processor Vendor: aarch64
        Processor Name:
        Identifier: aarch64 Family 8 Model 0xd0c Stepping r0x3p1
        Microarchitecture: unknown
        Frequency (GHz): -0.00
        Number of physical packages: 1
        Number of physical CPUs: 1
        Number of logical CPUs: 4
        Graphics card #0 name: Virtio GPU
        Graphics card #0 vendor: Red Hat, Inc.
        Graphics card #0 VRAM (MB): 0.00
        Graphics card #0 deviceId: unknown
        Graphics card #0 versionInfo: version: 01
        Virtual memory max (MB): 7982.02
        Virtual memory used (MB): 5080.46
        Swap memory total (MB): 0.00
        Swap memory used (MB): 0.00
        JVM Flags: 1 total; -Xms4G
        ModLauncher: 9.1.3+9.1.3+main.9b69c82a
        ModLauncher launch target: forgeserver
        ModLauncher naming: srg
        ModLauncher services:
                 mixin PLUGINSERVICE
                 eventbus PLUGINSERVICE
                 slf4jfixer PLUGINSERVICE
                 object_holder_definalize PLUGINSERVICE
                 runtime_enum_extender PLUGINSERVICE
                 capability_token_subclass PLUGINSERVICE
                 accesstransformer PLUGINSERVICE
                 runtimedistcleaner PLUGINSERVICE
                 mixin TRANSFORMATIONSERVICE
                 fml TRANSFORMATIONSERVICE
        FML Language Providers:
                minecraft@1.0
                lowcodefml@null
                kotori_scala@2.13.10-build-12
                javafml@null
Mod List:
                rsrequestify-2.2.0.jar                            |RSRequestify                  |rsrequestify                  |2.2.0               |SIDED_SETU|Manifest: NOSIGNATURE
                CyclopsCore-1.18.2-1.16.1.jar                     |Cyclops Core                  |cyclopscore                   |1.16.1              |SIDED_SETU|Manifest: NOSIGNATURE
                auudio_forge_1.0.3_MC_1.18-1.18.2.jar             |Auudio                        |auudio                        |1.0.3               |SIDED_SETU|Manifest: NOSIGNATURE
                auxiliaryblocks-1.18.2-0.4.1.jar                  |Auxiliary Blocks              |auxiliaryblocks               |1.18.2-0.4.1        |SIDED_SETU|Manifest: NOSIGNATURE
                supermartijn642configlib-1.1.6-forge-mc1.18.jar   |SuperMartijn642's Config Libra|supermartijn642configlib      |1.1.6               |SIDED_SETU|Manifest: NOSIGNATURE
                Architects-Palette-1.18.2-1.2.0.jar               |Architect's Palette           |architects_palette            |1.1.2               |SIDED_SETU|Manifest: NOSIGNATURE
                cagerium-1.18.2-1.1.0.jar                         |cagerium                      |cagerium                      |1.18.2-1.1.0        |SIDED_SETU|Manifest: NOSIGNATURE
                mcw-windows-2.1.1-mc1.18.2forge.jar               |Macaw's Windows               |mcwwindows                    |2.1.1               |SIDED_SETU|Manifest: NOSIGNATURE
                sophisticatedcore-1.18.2-0.5.37.202.jar           |Sophisticated Core            |sophisticatedcore             |1.18.2-0.5.37.202   |SIDED_SETU|Manifest: NOSIGNATURE
                rubidium-0.5.4.jar                                |Rubidium                      |rubidium                      |0.5.4               |SIDED_SETU|Manifest: NOSIGNATURE
                InitialInventory-forge-1.18.2-6.0.8.jar           |Initial Inventory             |initialinventory              |6.0.8               |SIDED_SETU|Manifest: NOSIGNATURE
                IronGenerators-2.0.2-1.18.2.jar                   |Iron Generators               |irongenerators                |2.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
                XaerosWorldMap_1.28.7_Forge_1.18.2.jar            |Xaero's World Map             |xaeroworldmap                 |1.28.7              |SIDED_SETU|Manifest: NOSIGNATURE
                cookingforblockheads-forge-1.18.2-12.2.0.jar      |CookingForBlockheads          |cookingforblockheads          |12.2.0              |SIDED_SETU|Manifest: NOSIGNATURE
                Controlling-forge-1.18.2-9.0+22.jar               |Controlling                   |controlling                   |9.0+22              |SIDED_SETU|Manifest: NOSIGNATURE
                Prism-1.18.2-1.0.1.jar                            |Prism                         |prism                         |1.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
                Placebo-1.18.2-6.2.0.jar                          |Placebo                       |placebo                       |6.2.0               |SIDED_SETU|Manifest: NOSIGNATURE
                citadel-1.11.3-1.18.2.jar                         |Citadel                       |citadel                       |1.11.3              |SIDED_SETU|Manifest: NOSIGNATURE
                alexsmobs-1.18.6.jar                              |Alex's Mobs                   |alexsmobs                     |1.18.6              |SIDED_SETU|Manifest: NOSIGNATURE
                Powah-3.0.7.jar                                   |Powah                         |powah                         |3.0.7               |SIDED_SETU|Manifest: NOSIGNATURE
                Bookshelf-Forge-1.18.2-13.2.51.jar                |Bookshelf                     |bookshelf                     |13.2.51             |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
                lootbeams-1.18.1-release-july1722.jar             |LootBeams                     |lootbeams                     |1.18.1              |SIDED_SETU|Manifest: NOSIGNATURE
                twigs-1.1.4-patch4+1.18.2-forge.jar               |Twigs                         |twigs                         |1.1.4-patch4+1.18.2 |SIDED_SETU|Manifest: NOSIGNATURE
                buildinggadgets-3.13.1-build.18+mc1.18.2.jar      |Building Gadgets              |buildinggadgets               |3.13.1-build.18+mc1.|SIDED_SETU|Manifest: NOSIGNATURE
                DarkUtilities-Forge-1.18.2-10.0.5.jar             |DarkUtilities                 |darkutils                     |10.0.5              |SIDED_SETU|Manifest: NOSIGNATURE
                mcw-doors-1.0.7-mc1.18.2.jar                      |Macaw's Doors                 |mcwdoors                      |1.0.7               |SIDED_SETU|Manifest: NOSIGNATURE
                MekanismGenerators-1.18.2-10.2.5.465.jar          |Mekanism: Generators          |mekanismgenerators            |10.2.5              |SIDED_SETU|Manifest: NOSIGNATURE
                balm-3.2.1+0.jar                                  |Balm                          |balm                          |3.2.1+0             |SIDED_SETU|Manifest: NOSIGNATURE
                JustEnoughResources-1.18.2-0.14.1.171.jar         |Just Enough Resources         |jeresources                   |0.14.1.171          |SIDED_SETU|Manifest: NOSIGNATURE
                cloth-config-6.3.81-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.3.81              |SIDED_SETU|Manifest: NOSIGNATURE
                shetiphiancore-1.18-3.10.12.jar                   |ShetiPhian-Core               |shetiphiancore                |3.10.12             |SIDED_SETU|Manifest: NOSIGNATURE
                MmmMmmMmmMmm-1.18.2-1.5.2.jar                     |MmmMmmMmmMmm                  |dummmmmmy                     |1.18-1.5.2          |SIDED_SETU|Manifest: NOSIGNATURE
                refinedstorage-1.10.4.jar                         |Refined Storage               |refinedstorage                |1.10.4              |SIDED_SETU|Manifest: NOSIGNATURE
                konkrete_forge_1.6.0_MC_1.18-1.18.2.jar           |Konkrete                      |konkrete                      |1.6.0               |SIDED_SETU|Manifest: NOSIGNATURE
                easy_piglins-1.18.2-1.0.4.jar                     |Easy Piglins                  |easy_piglins                  |1.18.2-1.0.4        |SIDED_SETU|Manifest: NOSIGNATURE
                corpse-1.18.2-1.0.2.jar                           |Corpse                        |corpse                        |1.18.2-1.0.2        |SIDED_SETU|Manifest: NOSIGNATURE
                PackMenu-1.18.2-4.1.3.jar                         |PackMenu                      |packmenu                      |4.1.3               |SIDED_SETU|Manifest: NOSIGNATURE
                mcw-bridges-2.0.6-mc1.18.2forge.jar               |Macaw's Bridges               |mcwbridges                    |2.0.6               |SIDED_SETU|Manifest: NOSIGNATURE
                torchmaster-18.1.0.jar                            |Torchmaster                   |torchmaster                   |18.1.0              |SIDED_SETU|Manifest: NOSIGNATURE
                Compressium-1.4.2-build.9+mc1.18.2.jar            |Compressium                   |compressium                   |1.4.2-build.9+mc1.18|SIDED_SETU|Manifest: NOSIGNATURE
                Ping-1.18-1.8.0.jar                               |Ping                          |ping                          |1.18-1.8.0          |SIDED_SETU|Manifest: NOSIGNATURE
                ironfurnaces-1.18.2-3.3.3.jar                     |Iron Furnaces                 |ironfurnaces                  |3.3.3               |SIDED_SETU|Manifest: NOSIGNATURE
                mcw-trapdoors-1.0.8-mc1.18.2forge.jar             |Macaw's Trapdoors             |mcwtrpdoors                   |1.0.8               |SIDED_SETU|Manifest: NOSIGNATURE
                mcw-fences-1.0.7-mc1.18.2forge.jar                |Macaw's Fences and Walls      |mcwfences                     |1.0.7               |SIDED_SETU|Manifest: NOSIGNATURE
                supermartijn642corelib-1.0.19-forge-mc1.18.jar    |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.19              |SIDED_SETU|Manifest: NOSIGNATURE
                simplylight-1.18.2-1.4.5-build.43.jar             |Simply Light                  |simplylight                   |1.18.2-1.4.5-build.4|SIDED_SETU|Manifest: NOSIGNATURE
                Botania-1.18.2-435.jar                            |Botania                       |botania                       |1.18.2-435          |SIDED_SETU|Manifest: NOSIGNATURE
                fairylights-5.0.0-1.18.2.jar                      |Fairy Lights                  |fairylights                   |5.0.0               |SIDED_SETU|Manifest: NOSIGNATURE
                Highlighter-1.18.1-1.1.2.jar                      |Highlighter                   |highlighter                   |1.1.2               |SIDED_SETU|Manifest: NOSIGNATURE
                spark-1.9.11-forge.jar                            |spark                         |spark                         |1.9.11              |SIDED_SETU|Manifest: NOSIGNATURE
                curios-forge-1.18.2-5.0.7.1.jar                   |Curios API                    |curios                        |1.18.2-5.0.7.1      |SIDED_SETU|Manifest: NOSIGNATURE
                Patchouli-1.18.2-71.1.jar                         |Patchouli                     |patchouli                     |1.18.2-71.1         |SIDED_SETU|Manifest: NOSIGNATURE
                camera-1.18.2-1.0.5.jar                           |Camera Mod                    |camera                        |1.18.2-1.0.5        |SIDED_SETU|Manifest: NOSIGNATURE
                blockcarpentry-1.18-0.3.0.jar                     |BlockCarpentry                |blockcarpentry                |1.18-0.3.0          |SIDED_SETU|Manifest: NOSIGNATURE
                libnonymous-2.1.0.jar                             |libnonymous                   |libnonymous                   |2.1.0               |SIDED_SETU|Manifest: NOSIGNATURE
                elevatorid-1.18.2-1.8.4.jar                       |Elevator Mod                  |elevatorid                    |1.18.2-1.8.4        |SIDED_SETU|Manifest: NOSIGNATURE
                Runelic-Forge-1.18.2-11.0.1.jar                   |Runelic                       |runelic                       |11.0.1              |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
                cfm-7.0.0-pre29-1.18.2.jar                        |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre29         |SIDED_SETU|Manifest: NOSIGNATURE
                architectury-4.10.88-forge.jar                    |Architectury                  |architectury                  |4.10.88             |SIDED_SETU|Manifest: NOSIGNATURE
                weirdinggadget-1.18.1-2.2.11.jar                  |The Weirding Gadget           |weirdinggadget                |2.2.11              |SIDED_SETU|Manifest: NOSIGNATURE
                mcw-furniture-3.0.2-mc1.18.2.jar                  |Macaw's Furniture             |mcwfurnitures                 |3.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
                trashcans-1.0.15-forge-mc1.18.jar                 |Trash Cans                    |trashcans                     |1.0.15              |SIDED_SETU|Manifest: NOSIGNATURE
                mcw-lights-1.0.4-mc1.18.2.jar                     |Macaw's Lights and Lamps      |mcwlights                     |1.0.4               |SIDED_SETU|Manifest: NOSIGNATURE
                Cucumber-1.18.2-5.1.3.jar                         |Cucumber Library              |cucumber                      |5.1.3               |SIDED_SETU|Manifest: NOSIGNATURE
                Snad-1.18.2-1.22.04.15a.jar                       |Snad                          |snad                          |1.18.2-1.22.04.15a  |SIDED_SETU|Manifest: NOSIGNATURE
                jei-1.18.2-9.7.2.281.jar                          |Just Enough Items             |jei                           |9.7.2.281           |SIDED_SETU|Manifest: NOSIGNATURE
                bdlib-1.19.3.7-mc1.18.2.jar                       |BdLib                         |bdlib                         |1.19.3.7            |SIDED_SETU|Manifest: NOSIGNATURE
                waystones-forge-1.18.2-10.1.0.jar                 |Waystones                     |waystones                     |10.1.0              |SIDED_SETU|Manifest: NOSIGNATURE
                Clumps-forge-1.18.2-8.0.0+17.jar                  |Clumps                        |clumps                        |8.0.0+17            |SIDED_SETU|Manifest: NOSIGNATURE
                shutupexperimentalsettings-1.0.5.jar              |Shutup Experimental Settings! |shutupexperimentalsettings    |1.0.5               |SIDED_SETU|Manifest: NOSIGNATURE
                comforts-forge-1.18.2-5.0.0.5.jar                 |Comforts                      |comforts                      |1.18.2-5.0.0.5      |SIDED_SETU|Manifest: NOSIGNATURE
                NaturesCompass-1.18.2-1.9.7-forge.jar             |Nature's Compass              |naturescompass                |1.18.2-1.9.7-forge  |SIDED_SETU|Manifest: NOSIGNATURE
                SimpleStorageNetwork-1.18.2-1.6.2.jar             |Simple Storage Network        |storagenetwork                |1.18.2-1.6.2        |SIDED_SETU|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
                framedcompactdrawers-1.18-4.1.0.jar               |Framed Compacting Drawers     |framedcompactdrawers          |1.18-4.1.0          |SIDED_SETU|Manifest: NOSIGNATURE
                Decorative Blocks-forge-1.18.2-2.1.2.jar          |Decorative Blocks             |decorative_blocks             |2.1.2               |SIDED_SETU|Manifest: NOSIGNATURE
                BotanyPots-Forge-1.18.2-8.0.23.jar                |BotanyPots                    |botanypots                    |8.0.23              |SIDED_SETU|Manifest: NOSIGNATURE
                ftbbackups2-forge-1.18.2-1.0.17.jar               |FTB Backups 2                 |ftbbackups2                   |1.0.17              |SIDED_SETU|Manifest: NOSIGNATURE
                mcjtylib-1.18-6.0.20.jar                          |McJtyLib                      |mcjtylib                      |1.18-6.0.20         |SIDED_SETU|Manifest: NOSIGNATURE
                rftoolsbase-1.18-3.0.11.jar                       |RFToolsBase                   |rftoolsbase                   |1.18-3.0.11         |SIDED_SETU|Manifest: NOSIGNATURE
                xnet-1.18-4.0.7.jar                               |XNet                          |xnet                          |1.18-4.0.7          |SIDED_SETU|Manifest: NOSIGNATURE
                ispawner-1.0.5-forge.jar                          |iSpawner                      |ispawner                      |1.0                 |SIDED_SETU|Manifest: NOSIGNATURE
                everycomp-1.18.2-1.5.15.jar                       |Every Compat                  |everycomp                     |1.18.2-1.5.15       |SIDED_SETU|Manifest: NOSIGNATURE
                JEITweaker-1.18.2-3.0.0.9.jar                     |JEI Tweaker                   |jeitweaker                    |3.0.0.9             |SIDED_SETU|Manifest: NOSIGNATURE
                Terralith_v2.2.3.jar                              |Terralith                     |terralith                     |0.0NONE             |SIDED_SETU|Manifest: NOSIGNATURE
                mininggadgets-1.11.1.jar                          |Mining Gadgets                |mininggadgets                 |1.11.1              |SIDED_SETU|Manifest: NOSIGNATURE
                CraftTweaker-forge-1.18.2-9.1.197.jar             |CraftTweaker                  |crafttweaker                  |9.1.197             |SIDED_SETU|Manifest: NOSIGNATURE
                Mekanism-1.18.2-10.2.5.465.jar                    |Mekanism                      |mekanism                      |10.2.5              |SIDED_SETU|Manifest: NOSIGNATURE
                forge-1.18.2-40.2.0-universal.jar                 |Forge                         |forge                         |40.2.0              |SIDED_SETU|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
                Waddles-1.18.2-0.8.19.jar                         |Waddles                       |waddles                       |1.18.2-0.8.19       |SIDED_SETU|Manifest: NOSIGNATURE
                ColossalChests-1.18.2-1.8.3.jar                   |ColossalChests                |colossalchests                |1.8.3               |SIDED_SETU|Manifest: NOSIGNATURE
                selene-1.18.2-1.17.9.jar                          |Selene                        |selene                        |1.18.2-1.17.9       |SIDED_SETU|Manifest: NOSIGNATURE
                supplementaries-1.18.2-1.5.14.jar                 |Supplementaries               |supplementaries               |1.18.2-1.5.14       |SIDED_SETU|Manifest: NOSIGNATURE
                drippyloadingscreen_forge_1.6.6_MC_1.18-1.18.2.jar|Drippy Loading Screen         |drippyloadingscreen           |1.6.6               |SIDED_SETU|Manifest: NOSIGNATURE
                craftingtweaks-forge-1.18.2-14.0.3.jar            |CraftingTweaks                |craftingtweaks                |14.0.3              |SIDED_SETU|Manifest: NOSIGNATURE
                server-1.18.2-20220404.173914-srg.jar             |Minecraft                     |minecraft                     |1.18.2              |SIDED_SETU|Manifest: NOSIGNATURE
                cofh_core-1.18.2-9.1.2.32.jar                     |CoFH Core                     |cofh_core                     |9.1.2.32            |SIDED_SETU|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
                thermal_foundation-1.18.2-9.1.0.34.jar            |Thermal Series                |thermal                       |9.1.0.34            |SIDED_SETU|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
                thermal_expansion-1.18.2-9.1.0.18.jar             |Thermal Expansion             |thermal_expansion             |9.1.0.18            |SIDED_SETU|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
                TerraBlender-forge-1.18.2-1.2.0.126.jar           |TerraBlender                  |terrablender                  |1.2.0.126           |SIDED_SETU|Manifest: NOSIGNATURE
                sophisticatedbackpacksvh-1.18.2-1.0.5.13.jar      |Sophisticated Backpacks Vault |sophisticatedbackpacksvh      |1.18.2-1.0.5.13     |SIDED_SETU|Manifest: NOSIGNATURE
                sophisticatedbackpacks-1.18.2-3.18.40.777.jar     |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.2-3.18.40.777  |SIDED_SETU|Manifest: NOSIGNATURE
                MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |SIDED_SETU|Manifest: NOSIGNATURE
                titanium-1.18.2-3.5.8-40.jar                      |Titanium                      |titanium                      |3.5.8               |SIDED_SETU|Manifest: NOSIGNATURE
                Jade-1.18.2-forge-5.2.6.jar                       |Jade                          |jade                          |5.2.6               |SIDED_SETU|Manifest: NOSIGNATURE
                appliedenergistics2-forge-11.7.0.jar              |Applied Energistics 2         |ae2                           |11.7.0              |SIDED_SETU|Manifest: NOSIGNATURE
                CreateTweaker-1.18.2-2.0.0.17.jar                 |CreateTweaker                 |createtweaker                 |2.0.0.17            |SIDED_SETU|Manifest: NOSIGNATURE
                easy_villagers-1.18.2-1.0.11.jar                  |Easy Villagers                |easy_villagers                |1.18.2-1.0.11       |SIDED_SETU|Manifest: NOSIGNATURE
                pipez-1.18.2-1.1.5.jar                            |Pipez                         |pipez                         |1.18.2-1.1.5        |SIDED_SETU|Manifest: NOSIGNATURE
                Iceberg-1.18.2-forge-1.0.49.jar                   |Iceberg                       |iceberg                       |1.0.49              |SIDED_SETU|Manifest: NOSIGNATURE
                flywheel-forge-1.18.2-0.6.8.jar                   |Flywheel                      |flywheel                      |0.6.8-97            |SIDED_SETU|Manifest: NOSIGNATURE
                create-1.18.2-0.5.0.g.jar                         |Create                        |create                        |0.5.0.g             |SIDED_SETU|Manifest: NOSIGNATURE
                Mantle-1.18.2-1.9.31.jar                          |Mantle                        |mantle                        |1.9.31              |SIDED_SETU|Manifest: NOSIGNATURE
                ecologics-forge-1.18.2-1.7.11.jar                 |Ecologics                     |ecologics                     |1.7.11              |SIDED_SETU|Manifest: NOSIGNATURE
                Xaeros_Minimap_22.17.0_Forge_1.18.2.jar           |Xaero's Minimap               |xaerominimap                  |22.17.0             |SIDED_SETU|Manifest: NOSIGNATURE
                PigPen-Forge-1.18.2-8.0.1.jar                     |PigPen                        |pigpen                        |8.0.1               |SIDED_SETU|Manifest: NOSIGNATURE
                FastWorkbench-1.18.2-6.0.2.jar                    |Fast Workbench                |fastbench                     |6.0.2               |SIDED_SETU|Manifest: NOSIGNATURE
                polymorph-forge-1.18.2-0.46.jar                   |Polymorph                     |polymorph                     |1.18.2-0.46         |SIDED_SETU|Manifest: NOSIGNATURE
                AutoRegLib-1.7-53.jar                             |AutoRegLib                    |autoreglib                    |1.7-53              |SIDED_SETU|Manifest: NOSIGNATURE
                AkashicTome-1.5-20.jar                            |Akashic Tome                  |akashictome                   |1.5-20              |SIDED_SETU|Manifest: NOSIGNATURE
                Quark-3.2-358.jar                                 |Quark                         |quark                         |3.2-358             |SIDED_SETU|Manifest: NOSIGNATURE
                StorageDrawers-1.18.2-10.2.1.jar                  |Storage Drawers               |storagedrawers                |10.2.1              |SIDED_SETU|Manifest: NOSIGNATURE
                FluxNetworks-1.18.2-7.0.8.12.jar                  |Flux Networks                 |fluxnetworks                  |7.0.8.12            |SIDED_SETU|Manifest: NOSIGNATURE
                neoncraft2-2.2.jar                                |Neon Craft 2                  |neoncraft2                    |2.2                 |SIDED_SETU|Manifest: NOSIGNATURE
                enercell-1.18.2-1.0.2.jar                         |Enercell                      |enercell                      |0.0NONE             |SIDED_SETU|Manifest: NOSIGNATURE
                appleskin-forge-mc1.18.2-2.4.1.jar                |AppleSkin                     |appleskin                     |2.4.1+mc1.18.2      |SIDED_SETU|Manifest: NOSIGNATURE
                ferritecore-4.2.2-forge.jar                       |Ferrite Core                  |ferritecore                   |4.2.2               |SIDED_SETU|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
                modular-routers-1.18.2-9.1.1-93.jar               |Modular Routers               |modularrouters                |9.1.1-93            |SIDED_SETU|Manifest: NOSIGNATURE
                refinedstorageaddons-0.8.2.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.8.2               |SIDED_SETU|Manifest: NOSIGNATURE
                OpenLoader-Forge-1.18.2-12.0.1.jar                |OpenLoader                    |openloader                    |12.0.1              |SIDED_SETU|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
                the_vault-1.18.2-2.0.14.1200.jar                  |The Vault                     |the_vault                     |1.18.2-2.0.14.1200  |ERROR     |Manifest: NOSIGNATURE
        Crash Report UUID: 08e86aca-2d34-4d5e-bf99-871ac605f9d3
        FML: 40.2
        Forge: net.minecraftforge:40.2.0[03:46:55] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        The Vault (the_vault) encountered an error during the common_setup event phase
§7java.lang.NullPointerException: Cannot invoke "iskallia.vault.core.world.template.data.TemplatePool.iterate(java.util.function.Predicate)" because "pool" is null
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:222) ~[fmlcore-1.18.2-40.2.0.jar%23170!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$21(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.0.jar%23170!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin,re:computing_frames}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:187) ~[fmlcore-1.18.2-40.2.0.jar%23170!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$loadMods$14(ModLoader.java:170) ~[fmlcore-1.18.2-40.2.0.jar%23170!/:?] {}
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:170) ~[fmlcore-1.18.2-40.2.0.jar%23170!/:?] {}
        at net.minecraftforge.server.loading.ServerModLoader.load(ServerModLoader.java:33) ~[forge-1.18.2-40.2.0-universal.jar%23174!/:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:112) ~[server-1.18.2-20220404.173914-srg.jar%23169!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$launchService$0(CommonServerLaunchHandler.java:32) ~[fmlloader-1.18.2-40.2.0.jar%2317!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
java.lang.NullPointerException: Cannot invoke "net.creeperhost.ftbbackups.org.quartz.Scheduler.isShutdown()" because "net.creeperhost.ftbbackups.FTBBackups.scheduler" is null
        at TRANSFORMER/ftbbackups2@1.0.17/net.creeperhost.ftbbackups.FTBBackups.killOutThreads(FTBBackups.java:110)
        at java.base/java.lang.Thread.run(Thread.java:833)
``

**Comment by jmilthedude** [comment]
You need to download and set up the server files. There are tutorials for how to set up forge servers out there. This specific issue is because you are missing config files. Which are in the server files on CF.
