### ISSUE TITLE
the Vault Jar crashes my game...

### ISSUE THREAD

**Issue by soundtechscott** [Iskallia/Vault-public#191]
I have forge 35.1.28 and 35.1.37, both crash

[02Apr2021 16:11:36.674] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, scottydoodah, --version, 1.16.4-forge-35.1.37, --gameDir, C:\Users\Scott Evans\AppData\Roaming\.minecraft\Modded 1.16, --assetsDir, C:\Users\Scott Evans\AppData\Roaming\.minecraft\assets, --assetIndex, 1.16, --uuid, e31a15cc8da7402792290269e820794f, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 35.1.37, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201102.104115]
[02Apr2021 16:11:36.678] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_51 by Oracle Corporation
[02Apr2021 16:11:36.690] [main/WARN] [cpw.mods.modlauncher.SecureJarHandler/]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[02Apr2021 16:11:36.989] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[02Apr2021 16:11:37.020] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/Scott%20Evans/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[02Apr2021 16:11:38.665] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 13:0 token recognition error at: '`'
[02Apr2021 16:11:39.300] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [shetiphian.core.mixins.MixinConnector]
[02Apr2021 16:11:39.301] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.botania.common.MixinConnector]
[02Apr2021 16:11:39.301] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [vazkii.patchouli.common.MixinConnector]
[02Apr2021 16:11:39.303] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [nikita488.zycraft.mixin.ZYMixinConnector]
[02Apr2021 16:11:39.305] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [iskallia.vault.MixinConnector]
[02Apr2021 16:11:39.311] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, 1.16.4-forge-35.1.37, --gameDir, C:\Users\Scott Evans\AppData\Roaming\.minecraft\Modded 1.16, --assetsDir, C:\Users\Scott Evans\AppData\Roaming\.minecraft\assets, --uuid, e31a15cc8da7402792290269e820794f, --username, scottydoodah, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release]
[02Apr2021 16:11:42.427] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[02Apr2021 16:11:42.427] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[02Apr2021 16:11:42.428] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[02Apr2021 16:11:42.428] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[02Apr2021 16:11:42.428] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[02Apr2021 16:11:42.428] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[02Apr2021 16:11:42.428] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[02Apr2021 16:11:42.428] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[02Apr2021 16:11:42.428] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[02Apr2021 16:11:42.428] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[02Apr2021 16:11:42.428] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[02Apr2021 16:11:42.428] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[02Apr2021 16:11:42.428] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$483/298259383.call(Unknown Source)
[02Apr2021 16:11:42.429] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[02Apr2021 16:11:42.429] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[02Apr2021 16:11:42.429] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: Caused by: java.lang.RuntimeException: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[02Apr2021 16:11:42.429] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:43)
[02Apr2021 16:11:42.429] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(Main.java:123)
[02Apr2021 16:11:42.429] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[02Apr2021 16:11:42.429] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[02Apr2021 16:11:42.429] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[02Apr2021 16:11:42.429] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[02Apr2021 16:11:42.429] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[02Apr2021 16:11:42.429] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[02Apr2021 16:11:42.430] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[02Apr2021 16:11:42.430] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[02Apr2021 16:11:42.430] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[02Apr2021 16:11:42.430] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[02Apr2021 16:11:42.430] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[02Apr2021 16:11:42.430] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[02Apr2021 16:11:42.430] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[02Apr2021 16:11:42.430] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.block.Blocks.<clinit>(Blocks.java:394)
[02Apr2021 16:11:42.430] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[02Apr2021 16:11:42.430] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[02Apr2021 16:11:42.430] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.lambda$static$0(WorldGenRegistries.java:33)
[02Apr2021 16:11:42.430] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$645/1375196140.get(Unknown Source)
[02Apr2021 16:11:42.430] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.lambda$static$6(WorldGenRegistries.java:89)
[02Apr2021 16:11:42.431] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries$$Lambda$653/1505674250.accept(Unknown Source)
[02Apr2021 16:11:42.431] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
[02Apr2021 16:11:42.431] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[02Apr2021 16:11:42.431] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[02Apr2021 16:11:42.431] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[02Apr2021 16:11:42.431] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:123)
[02Apr2021 16:11:42.431] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at net.minecraft.client.main.Main$$Lambda$591/1933965693.run(Unknown Source)
[02Apr2021 16:11:42.431] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[02Apr2021 16:11:42.431] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[02Apr2021 16:11:42.431] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[02Apr2021 16:11:42.431] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[02Apr2021 16:11:42.431] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:667]: 	at java.lang.Thread.run(Thread.java:745)
[02Apr2021 16:11:42.432] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method overrideMaxRepairLevel(I)I in assets/the_vault/the_vault.mixins.json:MixinRepairContainer failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap the_vault.refmap.json
[02Apr2021 16:11:42.432] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[02Apr2021 16:11:42.432] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[02Apr2021 16:11:42.432] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[02Apr2021 16:11:42.432] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[02Apr2021 16:11:42.432] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[02Apr2021 16:11:42.432] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[02Apr2021 16:11:42.432] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[02Apr2021 16:11:42.432] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[02Apr2021 16:11:42.432] [main/INFO] [STDERR/]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 28 more

**Comment by BONNe** [comment]
The Vault plugin is not a mod pack. It is just a vault generation.

You need to use Vault Modpack which is available in curseforge.

**Comment by soundtechscott** [comment]
the whole pack is extremely laggy...
I only want the vault portion of it to add to my current mods list

**Comment by soundtechscott** [comment]
and optifine crashes the game when I I try to use the mod pack as well

**Comment by Enderized** [comment]
> and optifine crashes the game when I I try to use the mod pack as well

Optifine is not compatible with Vault Hunters.

**Comment by soundtechscott** [comment]
I play with 130 mods on another Instance, with 60-70 fps and no issues...
this vault mod pack is laggy and I only see 20 fps.....

this should not have been released like this....

**Comment by BONNe** [comment]
> the whole pack is extremely laggy...
> I only want the vault portion of it to add to my current mods list

VaultHunters requires 6 to 8 GB of Ram

**Comment by soundtechscott** [comment]
I have 32, and have it setup to use 8 on minecraft

**Comment by Enderized** [comment]
> I play with 130 mods on another Instance, with 60-70 fps and no issues...
> this vault mod pack is laggy and I only see 20 fps.....
> 
> this should not have been released like this....

I have no issues playing at all.
From what i've heard, if you are using AMD try to reduce MipMap Level to 0

And/Or you can try to add in Chlorine as a mod.

**Comment by BONNe** [comment]
> the whole pack is extremely laggy...
> I only want the vault portion of it to add to my current mods list

If you want to use just a VaultHunters plugin, you need to remove all other mod items that are in nbt schemas and loot tables. It is possible to do, but not an easy task.
