### ISSUE TITLE
Vault altar not accepting vault rocks.

### ISSUE THREAD

**Issue by Baggytrousers27** [Iskallia/Vault-public#371]
As a preamble, my knowledge of minecraft modding etc. is scattered and limited so any instructions should not assume technical competency on my part asn specifics would be appreciated.

Was able to, successfully, produce a vault crystal but afterwards the altar is no longer accepting new rocks.
Additionally the following errors appear after loading into a world.

> [ERROR] Parser Exception @ recipes_vault_hunters.zs:93:31:
> Could not find tag manager with folder 'minecraft'. Make sure it exists!
> (Each error is identical except the number
> 93:31:
> 129:5
> 135:5
> 141:5
> 147:5
> 153:5
> 184:5
> 189:5
> 220:51
> 225:5
> 231:5
> 250:37
> 255:5
> 261:5
> 267:5
> 273:5
> 279:5
> 389:5
> 400:5
> 406:5
> 412:5
> 418:5
> 483:35
> 514:5
> 

**To Reproduce**
To begin with this case may be an outlier due to method of installation which was as follows:

1. Downloaded vault hunters modpack via overwolf launcher.
2. Downloaded up to date versions of each mod that could be updated.
3. Created a blank, 1.16.5 forge (36.1.4) installation, located data/save files from overwolf installation and copied the lot into the new forge one.
4. Replaced all the 1.16.3 mods with their 1.16.5 counterparts.
5. Started it up through the regular minecraft launcher and it all functioned as intended, barring a few recipe conflicts solved with polymorph and a few extra added mods for quality of life (Would've taken several weeks, instead of just one, to make a single vault crystal without help from things like gobber and tconstruct)

**Expected behavior**

**Screenshots or Crash Report**
![2021-06-29_22 27 31](https://user-images.githubusercontent.com/15883796/123810749-00370800-d936-11eb-8640-0dd3494d0c92.png)

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version: 1.3 hotfix

**Additional context**
A transcript of the game output when right clicking a vault altar with a vault rock is as follows:
00:10:39.295
game
at iskallia.vault.config.VaultAltarConfig.generateItems(VaultAltarConfig.java:87) ~[?:1.0.3-public] {re:classloading}
00:10:39.295
game
at iskallia.vault.altar.AltarInfusionRecipe.<init>(AltarInfusionRecipe.java:26) ~[?:1.0.3-public] {re:classloading}
00:10:39.295
game
at iskallia.vault.world.data.PlayerVaultAltarData.lambda$getRecipe$0(PlayerVaultAltarData.java:45) ~[?:1.0.3-public] {re:classloading}
00:10:39.295
game
at iskallia.vault.world.data.PlayerVaultAltarData$$Lambda$28772/1917845523.apply(Unknown Source) ~[?:?] {}
00:10:39.295
game
at java.util.HashMap.computeIfAbsent(HashMap.java:1118) ~[?:1.8.0_51] {}
00:10:39.295
game
at iskallia.vault.world.data.PlayerVaultAltarData.getRecipe(PlayerVaultAltarData.java:45) ~[?:1.0.3-public] {re:classloading}
00:10:39.295
game
at iskallia.vault.block.VaultAltarBlock.onAddVaultRock(VaultAltarBlock.java:85) ~[?:1.0.3-public] {re:classloading}
00:10:39.295
game
at iskallia.vault.block.VaultAltarBlock.func_225533_a_(VaultAltarBlock.java:80) ~[?:1.0.3-public] {re:classloading}
00:10:39.295
game
at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640) ~[?:?] {re:mixin,re:classloading,xf:fml:forgeendertech:randomTickBlock,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:A}
00:10:39.295
game
at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:338) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:veinmining.mixins.json:PlayerInteractionManagerMixin,pl:mixin:A}
00:10:39.295
game
at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
00:10:39.295
game
at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
00:10:39.295
game
at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
00:10:39.295
game
at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:mixin,re:classloading}
00:10:39.295
game
at net.minecraft.network.PacketThreadUtil$$Lambda$27278/606755707.run(Unknown Source) ~[?:?] {}
00:10:39.295
game
at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
00:10:39.295
game
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
00:10:39.295
game
at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?] {re:mixin,re:computing_frames,re:classloading}
00:10:39.295
game
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
00:10:39.295
game
at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
00:10:39.295
game
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
00:10:39.295
game
at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
00:10:39.295
game
at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
00:10:39.295
game
at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
00:10:39.295
game
at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
00:10:39.295
game
at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
00:10:39.295
game
at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blame.mixins.json:MinecraftServerAccessor,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.MixinMinecraftServer,pl:mixin:APP:imm_ptl_mixins.json:common.dimension.MixinMinecraftServer_D,pl:mixin:APP:imm_ptl_mixins.json:common.portal_generation.MixinMinecraftServer_P,pl:mixin:APP:imm_ptl_peripheral_mixins.json:common.altius_world.MixinMinecraftServer_A,pl:mixin:A}
00:10:39.295
game
at net.minecraft.server.MinecraftServer$$Lambda$25896/227036783.run(Unknown Source) [?:?] {}

**Comment by waidesoper** [comment]
Yeah, the public mod is only for 1.16.3, there are code changes that need to be made to get it to work with 1.16.5.

**Comment by Baggytrousers27** [comment]
> 
> 
> Yeah, the public mod is only for 1.16.3, there are code changes that need to be made to get it to work with 1.16.5.

Ignoring the missing files and something about scripts, the vault altar worked fine in a previous world (Made 3 vault crystals and then died in a vault because lost track of the exit) and in a new world. Backup says the file size is over a gig so that may be an issue and peculiarly even going into creative does nothing to affect the altar/rocks.

**Comment by Baggytrousers27** [comment]
Might have found the issue. If any other mod alters the luck effect (Everlasting abilities, charms etc.) any chests (in and outside of the vault) and the Vault altar become inaccessible.
