### ISSUE TITLE
World stops loading

### ISSUE THREAD

**Issue by rebelrose2310** [Iskallia/Vault-public#455]
**Describe the bug**
After loading the world, and traveling for quite a while the world border stops loading and the blocks I break do not drop (I can place blocks/saplings). Non-hostile mobs also do not move (I have not checked with hostile mobs) When I want to restart my game it goes to saving but never finished saving/keeps buffering and I have manually close the game by 'task management'(? my windows is in dutch so I don't know if this is the right term) (ctrl+alt+del). After restarting, when I open the world not everything is saved and I'm +- half a minute before the 'crash'. I don't know if this is a vault hunters bug or something else...

**To Reproduce**
1. Going to new areas/undiscovered areas in my world, not all the time but after walking for +- 1.5 minecraft days this issue starts happening
2. with restarting curseforge/the launcher the same issue appears
3. starting a new world does not work (tried 3 times)
4. I have cheats on

**Expected behavior**
I would expect the world to 

**Screenshots or Crash Report**
Normally I would forcefully close the game and would get code 0, but when I wanted to make a screenshot of the world 'border' I got this cash report
"The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Rendering entity in world
Afsluitcode: -1"

**Info (please complete the following information):**
- World Type: Single player
- The_Vault Version 1.5.1

**Comment by edwrenbeck** [comment]
I've experienced the same problem with all versions from 1.2 to 1.5.1. Single player worlds running locally. I haven't been able to gather a crash report, as the game just hangs and it has to be force quit from the task manager.

The only other anecdotal evidence I can add is that I can consistently get the game world to stop updating at the same spot in two different worlds. This happens when I start from a "Guidepost" (sign randomly in the world that says something like "200 bl ->") and move towards what the guidepost is pointing at.

It does not seem to be memory related. I have over 10GB on a 32GB machine dedicated. Sometimes when it looks up its consuming most of the RAM but I've also seen it stop world generation with 2-3 GB of available RAM.

I don't know what mod adds those guideposts to try disabling it.

**Comment by edwrenbeck** [comment]
Did a little more research. Found a stack trace that was dropped into the logs directory in the "latest.log" file. Included at the end here. Found a reference to the mode MCMT in the stack trace. This mod is not in the mod list, but the jar file is in the mods directory. At first I opened the file "configs/jmt_mcmt-common.toml" and set the Globally disabled property to true. That did not seem to have any effect. After that, I removed the jar file altogether and I was successfully able to load chunks that would not load previously. The gameplay does feel a little more laggy, with some stutters and GC type hangs. Have not played enough to determine if this true resolves the issue.

Relevant Stack Trace:
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathHeap.func_75846_b(SourceFile:118)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathHeap.func_75850_a(SourceFile:67)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathFinder.func_227479_a_(SourceFile:111)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathFinder.func_227478_a_(SourceFile:45)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathNavigator.func_225464_a(PathNavigator.java:129)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathNavigator.func_179680_a(PathNavigator.java:105)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathNavigator.func_188554_j(PathNavigator.java:78)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathNavigator.func_220970_c(PathNavigator.java:343)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.server.ServerWorld.func_184138_a(ServerWorld.java:1019)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.World.markAndNotifyBlock(World.java:232)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.World.func_241211_a_(World.java:212)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.World.func_180501_a(World.java:176)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.World.func_217377_a(World.java:260)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.block.LeavesBlock.func_225542_b_(LeavesBlock.java:42)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:624)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:508)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.jmt.mcmt.asmdest.ASMHookTerminator.lambda$callTickEnvironment$5(ASMHookTerminator.java:233)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.jmt.mcmt.asmdest.ASMHookTerminator$$Lambda$22571/761140760.run(Unknown Source)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
[20:16:10] [MCMT-Pool-Thread-31/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.NullPointerException
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathHeap.func_75847_a(SourceFile:81)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathHeap.func_75849_a(SourceFile:22)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathFinder.func_227479_a_(SourceFile:114)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathFinder.func_227478_a_(SourceFile:45)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathNavigator.func_225464_a(PathNavigator.java:129)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.pathfinding.PathNavigator.func_179680_a(PathNavigator.java:105)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.passive.BeeEntity$WanderGoal.func_75249_e(BeeEntity.java:1145)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.ai.goal.PrioritizedGoal.func_75249_e(SourceFile:41)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.ai.goal.GoalSelector.func_220877_a(SourceFile:83)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.ai.goal.GoalSelector$$Lambda$21886/455916937.accept(Unknown Source)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Iterator.forEachRemaining(Iterator.java:116)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.ai.goal.GoalSelector.func_75774_a(SourceFile:77)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.MobEntity.func_70626_be(MobEntity.java:682)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.LivingEntity.func_70636_d(LivingEntity.java:2411)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.MobEntity.func_70636_d(MobEntity.java:488)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.AgeableEntity.func_70636_d(SourceFile:127)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.passive.AnimalEntity.func_70636_d(AnimalEntity.java:51)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.passive.BeeEntity.func_70636_d(BeeEntity.java:401)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2158)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:300)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.entity.passive.BeeEntity.func_70071_h_(BeeEntity.java:218)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.jmt.mcmt.asmdest.ASMHookTerminator.lambda$callEntityTick$4(ASMHookTerminator.java:208)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.jmt.mcmt.asmdest.ASMHookTerminator$$Lambda$21714/1177056862.run(Unknown Source)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
[20:16:10] [MCMT-Pool-Thread-23/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[20:16:15] [Server thread/INFO]: Saving and pausing game...

**Comment by BONNe** [comment]
Jmt_Mcmt was removed from the pack at version 1.2

If it is still in your mod directory, remove it.

Other solution would be to perform clean pack installation.

**Comment by rebelrose2310** [comment]
I deleted the entire modpack from curseforge and re-downloaded it and I have not run in the same issue again, so perhaps it is indeed the Jmt_Mcmt still being in the mod directory!

**Comment by BONNe** [comment]
> I deleted the entire modpack from curseforge and re-downloaded it and I have not run in the same issue again, so perhaps it is indeed the Jmt_Mcmt still being in the mod directory!

Hmm, just downloaded the fresh 1.5.1 Pack version via Curseforge launcher in a new profile. MCMT mod _(which name in mods directory is jmt_mcmt)_ is not present.

**Comment by rebelrose2310** [comment]
Yeah, that's what I meant :') that in my previous version I did not delete the jmt_mcmt... I am however happy that my game is working again :)
