### ISSUE TITLE
Unable to create a vault crystal by using vault rock on the vault altar. Spams console with error.

### ISSUE THREAD

**Issue by Kunfury-blep** [Iskallia/Vault-public#470]
**Describe the bug**
Unable to create a vault crystal by using vault rock on the vault altar. Spams console with error.

**To Reproduce**
1. Get Vault Rock
2. Get Vault Altar
3. Right click Vault Altar with Vault Rock
4.

**Expected behavior**
Gives vault crystal? Not sure, going off of what people in discord have said.

**Screenshots or Crash Report**
`java.lang.NullPointerException: null
        at iskallia.vault.config.VaultAltarConfig.getRequiredItemsFromConfig(VaultAltarConfig.java:99) ~[the_vault:1.5p1.8.9] {re:classloading}
        at iskallia.vault.altar.AltarInfusionRecipe.<init>(AltarInfusionRecipe.java:28) ~[the_vault:1.5p1.8.9] {re:classloading}
        at iskallia.vault.world.data.PlayerVaultAltarData.lambda$getRecipe$0(PlayerVaultAltarData.java:40) ~[the_vault:1.5p1.8.9] {re:classloading}
        at java.util.HashMap.computeIfAbsent(HashMap.java:1127) ~[?:1.8.0_302] {}
        at iskallia.vault.world.data.PlayerVaultAltarData.getRecipe(PlayerVaultAltarData.java:40) ~[the_vault:1.5p1.8.9] {re:classloading}
        at iskallia.vault.block.entity.VaultAltarTileEntity.onAddVaultRock(VaultAltarTileEntity.java:166) ~[the_vault:1.5p1.8.9] {re:classloading}
        at iskallia.vault.block.VaultAltarBlock.func_225533_a_(VaultAltarBlock.java:75) ~[the_vault:1.5p1.8.9] {re:classloading}
        at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:338) ~[?:?] {re:computing_frames,re:classloading}
        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
        at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:mixin,re:classloading}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A,pl:runtimedistcleaner:A}
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_302] {}`

**Info (please complete the following information):**
- World Type: Server
- The_Vault Version: 1.5.1

**Additional context**
We had to go entirely off of what folks in the discord told us to do as there isn't anything in game that we could find that would teach us how to do this process.

**Comment by bmemike** [comment]
Have you tried restarting the server?

**Comment by Kunfury-blep** [comment]
Following further advice from the discord I went ahead and spawned in a
vault crystal, that worked but after entering the dimension and loading in
the server crashed and is now stuck in a boot loop.

**Comment by BONNe** [comment]
I would try to reinstall pack from the scratch.

**Comment by Kunfury-blep** [comment]
Reinstalling the pack with the latest update fixed this issue. Thank you.
