### ISSUE TITLE
iskallia.vault.integration.IntegrationMinimap spams logfile with a java.lang.NoSuchFieldException: showItems exception

### ISSUE THREAD

**Issue by bastetfurry** [Iskallia/Vault-public#676]
**Describe the bug**
The mod spams the logfile with a java.lang.NoSuchFieldException: showItems exception.

**To Reproduce**
1. Launch the modpack Vault Hunter in MultiMC
2. Watch the exception fill up the whole log

**Expected behavior**
No spamming of my log

**Screenshots or Crash Report**
```
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: java.lang.NoSuchFieldException: showItems
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at java.lang.Class.getDeclaredField(Class.java:2070)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at iskallia.vault.integration.IntegrationMinimap.setupConfigAccessors(IntegrationMinimap.java:101)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at iskallia.vault.integration.IntegrationMinimap.initialize(IntegrationMinimap.java:76)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at iskallia.vault.integration.IntegrationMinimap.onClientTick(IntegrationMinimap.java:119)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at net.minecraftforge.eventbus.ASMEventHandler_747_IntegrationMinimap_onClientTick_ClientTickEvent.invoke(.dynamic)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostClientTick(BasicEventHooks.java:110)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1544)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at net.minecraft.client.main.Main.main(Main.java:184)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[21:19:37] [Render thread/INFO] [STDERR/]: [iskallia.vault.integration.IntegrationMinimap:initialize:78]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

**Info (please complete the following information):**
- World Type: No game loaded, happens ingame too
- The_Vault Version: Vault+Hunters+-+Official+Modpack-1.12.1

**Comment by vikanezrimaya** [comment]
Same issue, but on my machine this makes the game unplayable - I've noticed that log spam correlates with huge performance drops.

**Comment by compilin** [comment]
~~I was gonna comment on how I had the same issue, including the performance drops (i.e huge lag spikes every 20s or so) but I seem to have accidentally fixed it. I remembered having some unrelated issue in another modpack and fixing it by changing the Java instance from the launcher's bundled one from my system's 1.8 install, so I tried that, aaand now there's no error spam or lag spikes anymore.~~

Nervermind spoke too soon, my log view wasn't updating, the error is actually still spamming, and the lag spikes seemed started again, although I'm not actually sure the two are related

**Comment by duhnyel** [comment]
i have the same issue and i think I'm gonna do some research that does it appear on older versions

**Comment by LogLauncher** [comment]
The newest version of the modpack 1.12.2 no longer has the log spam.
