### ISSUE TITLE
Crash when Loading Pack

### ISSUE THREAD

**Issue by KingAres4090** [Iskallia/Vault-public#702]
**Describe the bug**
The modpack crashes while minecraft is loading up.

**To Reproduce**
1.Launch Vault Hunters from MultiMC
2.Minecraft Starts Up
3.Minecraft Crashes while loading in mods

**Expected behavior**
I expected the pack to load in but Minecraft crashes after about 5-10 seconds

**Screenshots or Crash Report**
[14:13:57] [main/INFO] [STDERR/]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 1:0 token recognition error at: '~'
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:213]: Failed to start Minecraft:
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: java.lang.reflect.InvocationTargetException
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launch:245]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: Caused by: java.lang.reflect.InvocationTargetException
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
[14:13:59] [main/INFO] [STDERR/]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:214]: 	... 8 more
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoSuchMethodError: sun.security.util.ManifestEntryVerifier.<init>(Ljava/util/jar/Manifest;)V
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.SecureJarHandler.createCodeSource(SecureJarHandler.java:66)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:275)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.forName0(Native Method)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.Class.forName(Unknown Source)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:67)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.loadConnectors(MixinConnectorManager.java:70)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinConnectorManager.inject(MixinConnectorManager.java:59)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:196)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at java.util.HashMap.forEach(Unknown Source)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[14:13:59] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: 	... 13 more
[14:13:59] [main/INFO] [STDOUT/]: [org.multimc.EntryPoint:main:37]: Exiting with -1
Process exited with code -1.

**Info (please complete the following information):**
- World Type: Single Player
- The_Vault Version 1.12.2

**Additional context**
I've tried to reinstall the pack and even reinstall MultiMC but both have not fixed the issue.

**Comment by diavol619** [comment]
I have same issue and i tried to reinstall MultiMC, Vault Hunter Pack and Java but anything wont help :/

**Comment by diavol619** [comment]
You need to download adoptium openjdk. That way i got it work.
www.adoptium.net
